#!/bin/bash
#
# Copyright 2019-2024 MindShare Inc.
#
# Written for the Kubuntu Focus by M. Mikowski and A. Rainbolt.
#
# Name     : kfocus-chain-helper-reformat
# Summary  : kfocus-chain-helper-reformat <mount_point_type> <luks_yn>
#              <format_type> <target_partition_path>
# Purpose  : Reformats a partition and sets it up as an extra volume.
# Example  : kfocus-chain-helper-reformat home y format_disk /dev/nvme1n1p1
# License  : GPLv2
# Run By   : kfocus-chain-helper-ui
# Spec     : 4574
#
set -u;

## BEGIN _importCommonFn {
# Summary   : _importCommonFn
# Purpose   : Load common routines, prefer relative dir
# Example   : _importCommonFn;
# Arguments : none
# Globals   : Package vars _baseDir _baseName
# Outputs   : none
# Returns   : none
#
_importCommonFn () {
  declare _lib_list _is_loaded _lib_file;
  _lib_list=(
    "${_baseDir}/lib/common.2.source"
    '/usr/lib/kfocus/lib/common.2.source'
  );
  _is_loaded='n';
  for _lib_file in "${_lib_list[@]}"; do
    if [ -r "${_lib_file}" ]; then
      # shellcheck source=/usr/lib/kfocus/lib/common.2.source
      if source "${_lib_file}"; then
        _is_loaded='y';
        break;
      fi
    fi
  done

  if [ "${_is_loaded}" = 'n' ]; then
    echo 1>&2 "${_baseName}: ABORT - Cannot source common lib";
    exit 202;
  fi
}
## . END _importCommonFn }

## BEGIN _echoDebugFn {
_echoDebugFn () {
  [ "${_debugMode}" = 'n' ] && return;
  printf '%-10s: %s\n' 'DEBUG' "${1:-}" 1>&2;
}
## . END _echoDebugFn }

## BEGIN _getDataPartPathFn {
_getDataPartPathFn () {
  declare _line _mount_path _return_path _found_avail_path _part_idx;

  _return_path='/srv/data'
  _part_idx='1';

  while true; do
    _found_avail_path='y';
    while read -r _line; do
      _mount_path="$(awk '{print $2}' <<< "${_line}")";
      if [ "${_mount_path}" = "${_return_path}" ]; then
        _found_avail_path='n';
        break;
      fi
    done < /etc/fstab;

    if [ "${_found_avail_path}" = 'y' ]; then
      break;
    fi
    (( _part_idx++ )) || true;
    _return_path="/srv/data${_part_idx}";
  done

  echo "${_return_path}";
}
## . END _getDataPartPathFn }

## BEGIN _mainFn {
_mainFn () {
  declare _target_mount_type _luks_yn _disk_tgt _part_tgt _part_num \
    _crypt_tgt _key_tgt _default_str _mount_dev _mount_src _fstab_uuid_str \
    _format_mode _target_mount_point _part_uuid _part_label;

  # Determine useful paths and names
  _target_mount_type="${1:-}";
  [ -z "${_target_mount_type}" ] && exit 1;
  _luks_yn="${2:-}";
  [ -z "${_luks_yn}" ] && exit 1;
  _format_mode="${3:-}";
  [ -z "${_format_mode}" ] && exit 1;
  _part_tgt="${4:-}";
  [ -z "${_part_tgt}" ] && exit 1;
  _part_uuid="$(cat '/proc/sys/kernel/random/uuid')";
  [ -z "${_part_uuid}" ] && exit 1;
  _crypt_tgt="luks-${_part_uuid}";
  _key_tgt="luks-key-${_part_uuid}";
  if [[ "${_part_tgt}" =~ ^/dev/(sd[a-z]|vd[a-z]|xvd[a-z]) ]]; then
    _disk_tgt="/dev/${BASH_REMATCH[1]}";
  else
    _disk_tgt="${_part_tgt%p*}";
  fi
  [[ "${_part_tgt}" =~ ^/dev/.*[^0-9]([0-9]+) ]] || exit 1;
  _part_num="${BASH_REMATCH[1]}";
  _default_str="$(xxd -r -p <<< '6b7562756e74750a')";

  _echoDebugFn   "_disk_tgt  : ${_disk_tgt}";
  _echoDebugFn   "_part_tgt  : ${_part_tgt}";
  if [ "${_luks_yn}" = 'y' ]; then
    _echoDebugFn "_crypt_tgt : ${_crypt_tgt}";
    _echoDebugFn "_key_tgt   : ${_key_tgt}";
  fi

  # Partition the disk if needed
  if [ "${_format_mode}" = 'format_disk' ]; then
    echo -e 'label:gpt\n- - L -' | sfdisk -w always "${_disk_tgt}" || exit 2;
  fi

  # Format the partition
  if [ "${_luks_yn}" = 'y' ]; then
    _mount_dev="/dev/mapper/${_crypt_tgt}";
    echo "${_default_str}" | "${_cryptsetupExe}" luksFormat \
      --uuid "${_part_uuid}" "${_part_tgt}" || exit 2;
    echo "${_default_str}" \
      | "${_cryptsetupExe}" luksOpen "${_part_tgt}" "${_crypt_tgt}" \
      || exit 2;
    dd if=/dev/urandom of="/root/.${_key_tgt}" bs=1024 count=4 || exit 2;
    echo "${_default_str}" \
      | "${_cryptsetupExe}" luksAddKey "${_part_tgt}" "/root/.${_key_tgt}" \
      || exit 2;
    "${_ext4FormatExe}" "${_mount_dev}" || exit 2;
  else
    _mount_dev="${_part_tgt}";
    "${_ext4FormatExe}" -U "${_part_uuid}" "${_mount_dev}" || exit 2;
  fi

  # Determine target mount point
  if [ "${_target_mount_type}" = 'home' ]; then
    _target_mount_point='/home';
  else # "${_target_mount_point}" = 'data'
    _target_mount_point="$(_getDataPartPathFn)";
  fi

  # Label the partition
  _part_label="kfocus_$(basename "${_target_mount_point}")";
  sfdisk --part-label "${_disk_tgt}" "${_part_num}" "${_part_label}" \
    || exit 1;

  # Configure the disk to mount at boot
  _fstab_uuid_str="UUID=${_part_uuid}";
  if [ "${_luks_yn}" = 'y' ]; then
    _mount_src="${_mount_dev}";
    echo "${_crypt_tgt} ${_fstab_uuid_str} /root/.${_key_tgt} luks,discard" \
      >> /etc/crypttab || exit 2;
  else
    _mount_src="${_fstab_uuid_str}";
  fi
  echo -e "# KFOCUS ${_target_mount_point} is on ${_mount_dev}\n${_mount_src} ${_target_mount_point} ext4 defaults 0 2" >> /etc/fstab || exit 2;

  # Move the home directory if needed
  if [ "${_target_mount_type}" = 'home' ]; then
    # Unmount in preparation to move
    if mountpoint '/home' >/dev/null; then
      umount '/home' || exit 2;
    fi

    # Delete the unneeded home subvolume
    # Commented out because it makes the home dir conversion hard to revert.
    # "${_btrfsExe}" subvolume delete '/btrfs_main/@home' || exit 2;

    # Comment out the old /home mount line in fstab
    sed -i 's|^\(.*/home.*btrfs.*subvol=/@home.*\)$|# KFOCUS Replaced /home btrfs with extra disk\n# \1|' /etc/fstab || exit 2;
    # Re-parse fstab
    systemctl daemon-reload;
    # Remount /home
    mount '/home' || exit 2;
    # Get rid of a useless directory
    rmdir '/home/lost+found' || true;

  # Otherwise make sure the data partition actually exists
  else
    mkdir -p "${_target_mount_point}";
    mount "${_target_mount_point}" || exit 2;
    # Get rid of a useless directory
    rmdir "${_target_mount_point}/lost+found" || true;
  fi
}
## . END _mainFn }

## BEGIN Declare and assign global vars {
declare _binName _binDir _baseDir _baseName _debugMode _assignList \
  _cryptsetupExe _sfdiskExe _ext4FormatExe _btrfsExe;

_debugMode='y';
## . END Declare and assign global vars }

## BEGIN Run mainFn when script is NOT sourced {
if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then
  _binName="$(  readlink -f "$0"       )" || exit 101;
  _binDir="$(   dirname  "${_binName}" )" || exit 101;
  _baseDir="$(  dirname  "${_binDir}"  )" || exit 101;
  _baseName="$( basename "${_binName}" )" || exit 101;

  # Import libs and assign more global vars
  _importCommonFn;

  _assignList=(
    '_btrfsExe|/usr/bin/btrfs'
    '_cryptsetupExe|/usr/sbin/cryptsetup'
    '_ext4FormatExe|/usr/sbin/mkfs.ext4'
    '_sfdiskExe|/usr/sbin/sfdisk'
  );
  if ! _cm2AssignExeVarsFn "${_assignList[@]}"; then
    _cm2WarnStrFn 'ABORT: Required commands not found';
    exit 1;
  fi

  _mainFn "$@";
fi
## . END Run mainFn when script is NOT sourced }
