#!/bin/bash
#
# Enables OEM installaiton mode in Calamares.

if [ -e '/etc/calamares/OEM_MODE_ACTIVATED' ]; then
  export BROWSER='sudo -H -u kubuntu firefox'
  calamares -D8;
  exit;
fi

# Detect multi-disk and offer OEM mode if so
_disk_count=0;
IFS=$'\n' read -r -d '' -a _block_list <<< "$(
  find /dev/ -maxdepth 1 -type b \
  | grep -E '^/dev/(sd[a-z]|nvme[0-9]n1|vd[a-z])$'
)";
for _dev_file in "${_block_list[@]}"; do
    _byte_int="$(blockdev --getsize64 "${_dev_file}")";
  _mib_int=$(( _byte_int / 1048576 ));
  _trans_key="$(lsblk -ndo tran "${_dev_file}")";

  # Skip device if not the right disk type
  if ! [[ "${_trans_key}" =~ ^(sata|nvme|virtio)$ ]]; then
    continue;
  fi

  # Skip device if less than 64 GB
  if (( "${_mib_int}" < 65536 )); then
    continue;
  fi

  (( _disk_count++ )) || true;
done

_msg="$(cat <<EOL
<p>You are about to install the OS in OEM mode. This will prepare the system
for distribution to an end user, providing them with an account setup wizard.
If you do not need this capability, please cancel and use the normal install
method.</p>
EOL
)";

# Report multi-disk
if (( _disk_count > 1 )); then
  _msg+="$(cat <<EOL

<p>The system has multiple disks present. To properly configure a secondary
disk after installation, you MUST install the Kubuntu Focus Suite to a single
disk using a default installation option (such as Erase Disk). Do NOT use
manual partitioning, and do NOT change the default filesystem.</p>

<p>It is fine to enable encryption or disable the creation of a swap file if
desired. See <a
href="http://kfocus.org/wf/reinstall.html#bkm_multi_disk_configuration">http://kfocus.org/wf/reinstall.html#bkm_multi_disk_configuration</a>
for more information.</p>
EOL
  )";
fi

_msg+="$(cat <<EOL

<p>Are you sure you want to continue?</p>
EOL
)";

if kdialog --warningyesno "${_msg}"; then
  # Tweak branding to make it clear that OEM installation mode is active
  cp /etc/calamares/branding/kubuntu/welcome-oem.png /etc/calamares/branding/kubuntu/welcome.png;

  # Don't remove Calamares from the installed system.
  sed -i '/- calamares$/d' /etc/calamares/modules/packages.conf;

  # Enable oemid module, backslashes are needed for proper indentation
  sed -i "/- welcome$/a \ \ - oemid" /etc/calamares/settings.conf;

  # Enable OEM prep module
  sed -i "/- packages$/a \ \ - shellprocess@oemprep" /etc/calamares/settings.conf;

  # Fix OEM UID
  sed -i "/- shellprocess@oemprep$/a \ \ - shellprocess@fix-oem-uid" /etc/calamares/settings.conf;

  # Force the user of an OEM configuration user
  cp /etc/calamares/modules/users.conf.oem /etc/calamares/modules/users.conf;

  # Drop a file so that it can be seen that OEM installation mode is already
  # active
  touch /etc/calamares/OEM_MODE_ACTIVATED;

  # Launch Calamares
  export BROWSER='sudo -H -u kubuntu firefox'
  calamares -D8;
fi
