#!/bin/bash
#
# Enables OEM installation mode in Calamares.

if [ -e '/etc/calamares/OEM_MODE_ACTIVATED' ]; then
  export BROWSER='sudo -H -u kubuntu firefox'
  calamares -D8;
  exit;
fi

_msg="$(cat <<EOL
<p>You are about to install the OS in OEM mode. This will prepare the <br>
system for distribution to an end user, providing them with an account <br>
setup wizard. This is useful if you are reinstalling the OS on a Kubuntu <br>
Focus system, preparing a system for someone else, or installing onto a <br>
system with multiple disks.</p>

<p>Three different install methods are provided:</p>

<ul><li>Standard: Usual installation mode. Use if you want the main <br>
system disk to be dedicated to the root and boot partitions.</li>
<li>500 GB install: Same as Standard, but limits the size of the root <br>
partition to 500 GB and allocates any remaining space on the <br>
main system disk to an unformatted partition. The multi-disk <br>
configuration tool can then be used to configure this unformatted <br>
space as a home or data partition. Only use this mode if you are <br>
wiping the main system disk entirely.</li>
<li>Partition, then install: Launches KDE Partition Manager before <br>
launching the installer in Standard mode. This gives you the <br>
opportunity to delete the boot and root partitions of an old <br>
installation while preserving a home or data partition on the same <br>
disk. Use this mode if you are reinstalling Kubuntu and want to <br>
preserve a home or data partition.</li></ul>

<p>It is fine to enable encryption or disable the creation of a swap file if <br>
desired. See <br>
<a
href="https://kfocus.org/wf/reinstall.html#bkm_multi_disk_configuration">https://kfocus.org/wf/reinstall.html#bkm_multi_disk_configuration</a> <br>
for more information.</p>

<p>Select the desired install method, then click "OK" to continue.</p>
EOL
)";
_optionList=(
  'Standard' '500 GB install' 'Partition, then install' 'Cancel'
);

_ans="$(kdialog --combobox "${_msg}" "${_optionList[@]}")";
case "${_ans}" in
  'Standard')
    true;
    ;;
  '500 GB install')
    sed -i 's/size: 100%/size: 500G/' /etc/calamares/modules/partition.conf
    sed -i "/size: 500G$/a \ \ \ \ - name: 'kfocus_data'\n      filesystem: unformatted\n      size: 100%" /etc/calamares/modules/partition.conf
    ;;
  'Partition, then install')
    partitionmanager;
    ;;
  *)
    kdialog --msgbox "The OEM installation process has been cancelled.";
    exit 0;
    ;;
esac

# Tweak branding to make it clear that OEM installation mode is active
cp /etc/calamares/branding/kubuntu/welcome-oem.png /etc/calamares/branding/kubuntu/welcome.png;

# Don't remove Calamares from the installed system.
sed -i '/- calamares$/d' /etc/calamares/modules/packages.conf;

# Swap around the position of the kfocus-prep-user module
sed -i "/- shellprocess@kfocus-prep-user/d" /etc/calamares/settings.conf;
sed -i "/- packages$/a \ \ - shellprocess@kfocus-prep-user" /etc/calamares/settings.conf;

# Enable oemid module, backslashes are needed for proper indentation
sed -i "/- welcome$/a \ \ - oemid" /etc/calamares/settings.conf;

# Enable OEM prep module
sed -i "/- packages$/a \ \ - shellprocess@oemprep" /etc/calamares/settings.conf;

# Fix OEM UID
sed -i "/- shellprocess@oemprep$/a \ \ - shellprocess@fix-oem-uid" /etc/calamares/settings.conf;

# Force the user of an OEM configuration user
cp /etc/calamares/modules/users.conf.oem /etc/calamares/modules/users.conf;

# Drop a file so that it can be seen that OEM installation mode is already
# active
touch /etc/calamares/OEM_MODE_ACTIVATED;

# Launch Calamares
export BROWSER='sudo -H -u kubuntu firefox'
calamares -D8;
