## TODO 2026-06-23: Commented out kfocus-kclean, remove if no longer needed

usr/lib/kfocus/bin/kfocus-btool
usr/lib/kfocus/bin/kfocus-btool.d/m2g6.source
usr/lib/kfocus/bin/kfocus-check-crypt
usr/lib/kfocus/bin/kfocus-extra
usr/lib/kfocus/bin/kfocus-fix-ibus
usr/lib/kfocus/bin/kfocus-focusrx
usr/lib/kfocus/bin/kfocus-focusrx-set
usr/lib/kfocus/bin/kfocus-focusrx-system
usr/lib/kfocus/bin/kfocus-focusrx.d
# usr/lib/kfocus/bin/kfocus-kclean
# usr/lib/kfocus/bin/kfocus-kclean-set
usr/lib/kfocus/bin/kfocus-mime
usr/lib/kfocus/bin/kfocus-open-url-file
usr/lib/kfocus/bin/kfocus-reset-effects
usr/lib/kfocus/bin/kfocus-reset-widgets
usr/lib/kfocus/bin/kfocus-rx-version
usr/lib/kfocus/bin/kfocus-shrinkpdf
usr/lib/kfocus/bin/kfocus-sysreport
usr/lib/kfocus/bin/kfocus-web-launcher
usr/lib/kfocus/conf/etc_bash_completion.d_kfocus
usr/lib/kfocus/conf/etc_xdg_autostart_kfocus-focusrx-dbus-dispatch.desktop
usr/lib/kfocus/conf/etc_xdg_autostart_kfocus-focusrx.desktop
usr/lib/kfocus/conf/etc_xdg_menus_applications-merged_kfocus.menu
usr/lib/kfocus/plasma/*
usr/lib/systemd/system/*
usr/share/applications/kfocus-extra.desktop
usr/share/applications/kfocus-focusrx.desktop
usr/share/applications/kfocus-help.desktop
usr/share/applications/kfocus-mime.desktop
usr/share/applications/kfocus-open-url-file.desktop
usr/share/applications/kfocus-reset-effects.desktop
usr/share/applications/kfocus-reset-widgets.desktop
usr/share/applications/kfocus-passphrase-changer.desktop
usr/share/applications/kfocus-support-*.desktop
usr/share/icons/hicolor/scalable/apps/kfocus-bug-apps.svg
usr/share/icons/hicolor/scalable/apps/kfocus-bug-extra.svg
usr/share/icons/hicolor/scalable/apps/kfocus-bug-guided.svg
usr/share/icons/hicolor/scalable/apps/kfocus-bug-help.svg
usr/share/icons/hicolor/scalable/apps/kfocus-bug-kclean.svg
usr/share/icons/hicolor/scalable/apps/kfocus-bug-rx.svg
usr/share/icons/hicolor/scalable/apps/kfocus-bug-welcome.svg
usr/share/icons/hicolor/scalable/apps/kfocus-bug-widget.svg
usr/share/icons/hicolor/scalable/apps/kfocus-bug-wizard.svg
usr/share/icons/hicolor/scalable/apps/kfocus-bug-passphrase.svg
usr/share/kfocus-hints
usr/share/polkit-1/actions/org.kfocus.pkexec.kfocus-check-crypt.policy
usr/share/polkit-1/actions/org.kfocus.pkexec.kfocus-focusrx.policy
usr/share/polkit-1/actions/org.kfocus.pkexec.kfocus-mime.policy
# usr/share/polkit-1/actions/org.kfocus.pkexec.kfocus-kclean-set.policy
usr/share/user-manager
usr/share/X11
