#!/bin/bash
# kfocus-main preinst
#
# set -u is used to exist on uninitialized variables
#
# set -u; # uncomment to debug
set -e;

## { BEGIN Declare common.2.source symbols
#  IMPORT 2022-03-23 EXCERPT from test/test-scripts/common.2.source
_cm2Arg01="${1:-}";

_cm2BlockMsg='';
_cm2EchoFn    () { 1>&2 echo -e "$*";  }
_cm2SetMsgFn  () { _cm2BlockMsg="$*"; _cm2EchoFn "== BEGIN : ${_cm2BlockMsg}"; }
_cm2SucFn     () { _cm2EchoFn "== . END : OK   ${_cm2BlockMsg}\n\n"; }
_cm2WarnFn    () { _cm2EchoFn "== . END : WARN Could not ${_cm2BlockMsg}\n\n"; }
## } . END Declare common.2.source symbols

## BEGIN MAIN {
case "${_cm2Arg01}" in
  abort-upgrade)
  ;;

  install|upgrade)
    _cm2SetMsgFn 'Add i386 architecture for Vulkan';
    if ( dpkg --add-architecture i386 ); then
      _cm2SucFn; else _cm2WarnFn;
    fi
    _cm2SetMsgFn 'Divert language-selector pkg_depends file';
    if dpkg-divert --package 'kfocus-main' --add --rename --divert \
      '/usr/share/language-selector/data/pkg_depends.orig' \
      '/usr/share/language-selector/data/pkg_depends'; then
      _cm2SucFn;
    else
      _cm2WarnFn;
      exit 1;
    fi
  ;;
esac

exit 0;
## . END MAIN }

# Tag to allow some debhelper commands to inject relevant code
#DEBHELPER#
