#!/bin/bash
#
# Copyright 2024 - 2026 Lubuntu Developers <lubuntu-devel@lists.ubuntu.com>
# Copyright 2024 - 2026 Kubuntu Developers <kubuntu-devel@lists.ubuntu.com>
# Copyright 2024 - 2026 MindShare Inc.
#
# Adapted for the Kubuntu Focus from Kubuntu's Calamares scripts by
# A. Rainbolt.
#
# Name     : calamares-launch-normal
# Summary  : calamares-launch-normal
# Purpose  : Launches the Calamares installer normally.
# License  : GPLv2
# Run By   : Users
# Spec     : 6740
#
set -u;

## BEGIN _importCommonFn {
# Purpose: Import the common library with _cm2* symbols
#
_importCommonFn () {
  declare _lib_file;
  _lib_file="/usr/lib/kfocus/lib/common.2.source";
  if [ -r "${_lib_file}" ]; then
    # shellcheck source=../../package-main/usr/lib/kfocus/lib/common.2.source
    source "${_lib_file}" || exit 202;
  else
    echo 1>&2 "${_baseName}: ABORT - Cannot source lib |${_lib_file}|";
    exit 202;
  fi
}
## . END _importCommonFn }

## BEGIN _mainFn {
_mainFn () {
  local _brow_str _erow_str _header_str _table_str _win_title _icon_str \
    _msg _disk_count _dev_file _byte_int _mib_int _trans_key _block_list _ans;

  _brow_str='<tr><td style="padding:8px 32px 8px 0">';
  _erow_str='</td></tr>';
  _header_str='<h3 style="color:#f7941d">';
  _table_str='<table style="width:100%;margin-right:32px">';
  _win_title='Kubuntu 26.04 LTS with Focus Tools Installer';
  _icon_str='kfocus-bug-tools';

  # bashsupport disable=BP2001
  export QT_QPA_PLATFORMTHEME=kde

  if /usr/bin/calamares-m2g6-restrict; then
    # Prevent the restrict dialog from showing up twice on multi-disk systems
    # bashsupport disable=BP2001
    export CALAMARES_SKIP_M2G6_RESTRICT='y';
  else
    exit 1;
  fi

  if [ -e '/etc/calamares/OEM_MODE_ACTIVATED' ]; then
    _msg="$(cat <<EOL
${_cm2HtmBeginStr}${_table_str}
${_brow_str}${_header_str}OEM Install Needed</h3>${_erow_str}

${_brow_str}The installer was previously run in OEM mode. Please reboot <br>
to reset the configuration and try again.${_erow_str}</table>
${_cm2HtmEndStr}
EOL
    )";
    _cm2PromptUserFn "${_msg}" "${_win_title}";
    exit 1;
  fi

  # bashsupport disable=BP2001
  export BROWSER='sudo -H -u kubuntu firefox'

  # Detect multi-disk and offer OEM mode if so
  _disk_count=0;
  IFS=$'\n' read -r -d '' -a _block_list <<< "$(
    find /dev/ -maxdepth 1 -type b \
      | grep -E '^/dev/(sd[a-z]|nvme[0-9]n1|vd[a-z])$'
  )";
  for _dev_file in "${_block_list[@]}"; do
    _byte_int="$(sudo blockdev --getsize64 "${_dev_file}")";
    _mib_int=$(( _byte_int / 1048576 ));
    _trans_key="$(lsblk -ndo tran "${_dev_file}")";

    # Skip device if not the right disk type
    if ! [[ "${_trans_key}" =~ ^(sata|nvme|virtio)$ ]]; then
      continue;
    fi

    # Skip device if less than 64 GB
    if (( _mib_int < 65536 )); then
      continue;
    fi

    (( _disk_count++ )) || true;
  done

  # Report multi-disk
  if (( _disk_count > 1 )); then
    _msg="$(cat <<EOL
${_cm2HtmBeginStr}${_table_str}
${_brow_str}${_header_str}Multiple Disks Detected</h3>${_erow_str}

${_brow_str}The system has multiple disks present. If you intend to use <br>
one of these disks as a home or data disk, you should install <br>
Kubuntu Focus Suite using OEM mode. You will be able to <br>
configure the second disk after installation using the <br>
Multi-Disk Configuration Tool.${_erow_str}

${_brow_str}Launch OEM installer now?${_erow_str}</table>
${_cm2HtmEndStr}
EOL
    )";
    _ans="$(_cm2PromptUserFn -i "${_icon_str}" "${_msg}" "${_win_title}" 'a')";
    if [ "${_ans}" = 'y' ]; then
      exec calamares-launch-oem;
    fi
  fi

  sudo --preserve-env=XDG_CONFIG_DIRS BROWSER="${BROWSER}" calamares -D8;
}
## . END _mainFn }

## BEGIN Declare global variables {
declare _binName _binDir _baseDir _baseName
## . END Declare global variables }

## BEGIN Run main if the script is not sourced {
if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then
  _binName="$(  readlink -f "$0"        )" || exit 101;
  _binDir="$(   dirname  "${_binName}"  )" || exit 101;
  _baseDir="$(  dirname  "${_binDir}"   )" || exit 101;
  _baseName="$( basename "${_binName}")" || exit 101;
  _importCommonFn;

  _mainFn "$@";
fi
## . END Run main if the script is not sourced }
