update_db: true
ignore_update_db_error: true
backend: apt
operations:
  - remove:
      - "^live-*"
      - kfocus-calamares-settings
      - calamares
      - calamares-data
      - libcalamaresui3.3
      - cifs-utils
      - kfocus-installer-prompt
# The upstream calamares-settings-ubuntu package includes a 'try_install'
#   stanza which attempts to install language packs for '$LOCALE'. However, we
#   do not do this because language pack names in the repository have
#   variations. The packages that are specified here may not actually have a
#   package. For instance, 'libreoffice-help-en' does not exist,
#   'libreoffice-help-en-us' does. 'language-pack-kde-en-us' does not exist,
#   but 'language-pack-kde-en' does. No matter the value of '$LOCALE', one of
#   these two will result in a non-existant package. Besides, all English
#   locales are ignored according to
#   https://codeberg.org/Calamares/calamares/src/branch/calamares/src/modules/packages/packages.conf
#   (#6112, #6123).
