# We cannot safely update the apt database with 'update_db: true' without
#   risking a crash during installation (#6112). See:
#   https://codeberg.org/Calamares/calamares/issues/2474
update_db: false
backend: apt
operations:
  - remove:
      - calamares
