#!/bin/bash
#
# Copyright 2020-2023 MindShare Inc.
# Written for the Kubuntu Focus by Michael Mikowski and Erich Eickmeyer
#
set -e

## BEGIN MAIN {
# Only do complete clean-up on purge.
if [ "${1:-}" != "purge" ] ; then
  exit 0
fi

exit 0;
## . END MAIN }

# Tag to allow some debhelper commands to inject relevant code
#DEBHELPER#
