#!/bin/bash
# kfocus-apt-source postrm
# This must be run as root.
#
# set -u is used to exist on uninitialized variables
# set -e is not used as we do our own error checking
#
set -u;

[ $# -gt 0 ] && _cmd="${1}" || _cmd='';

## BEGIN MAIN {
# Only do complete clean-up on purge.
if [ "${_cmd}" != "purge" ] ; then
  exit 0
fi

exit 0;
## . END MAIN }

# Tag to allow some debhelper commands to inject relevant code
#DEBHELPER#
