#!/bin/bash
#
# Copyright 2020-2023 MindShare Inc.
# Written for the Kubuntu Focus by Michael Mikowski and Erich Eickmeyer
#
set -e;

## BEGIN MAIN {
case "${1:-}" in
  abort-upgrade) true;;
  install|upgrade|*)
    sed -i 's|^\(deb http://repo.kfocus.org/ubuntu/\? \)|# \1|g' \
      /etc/apt/sources.list
  ;;
esac

exit 0;
## . END MAIN }

# Tag to allow some debhelper commands to inject relevant code
#DEBHELPER#
