#!/bin/bash
# kfocus-apt-source preinst
# This must be run as root.
#
# See test/test-scripts/common.2.source for common routines when needed
#
# set -u is used to exist on uninitialized variables
# set -e is not used as we do our own error checking
#
set -u;

## BEGIN MAIN {
case "${1:-}" in
  abort-upgrade)
  ;;
  install|upgrade|*)
    sed -i 's|^\(deb http://repo.kfocus.org/ubuntu/\? \)|# \1|g' \
      /etc/apt/sources.list
  ;;
esac

exit 0;
## . END MAIN }

# Tag to allow some debhelper commands to inject relevant code
#DEBHELPER#
