#!/bin/bash
#
# Copyright 2020-2023 MindShare Inc.
# Written for the Kubuntu Focus by Michael Mikowski and Erich Eickmeyer
#
set -e;

_cmd="${1:-}";
_arg="${2:-}";

## BEGIN MAIN {
if [ "${_arg}" = 'in-favour' ]; then
  # Treat conflict remove as an upgrade
  _cmd='upgrade';
fi

# Do not clean-up just for an upgrade
if [ "${_cmd}" = 'upgrade' ] ; then
  exit 0
fi

exit 0;
## . END MAIN }

# Tag to allow some debhelper commands to inject relevant code
#DEBHELPER#
