#!/bin/bash
#
## BEGIN _updatePciidsFn {
#  Purpose  : Loads pci device details
#  Example  : _updatePciidsFn
#  Requires : common.2.source
#  Returns  : none
#  Throws   : none
#  Notes    :
#    This function always updates the database.
#    We delete /usr/share/misc/pci.ids.old because it is not properly
#    cleaned up per https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=950812
#
_updatePciidsFn () {
  declare _share_file _lspci_exe _update_exe;
  _share_file="${_rootDir}/usr/share/misc/pci.ids";
  _lspci_exe="$(  command -v lspci         || true)";
  _update_exe="$( command -v update-pciids || true)";

  _cm2SetMsgFn 'Update pciids';

  # Circumvent bug listed above
  if ! "${_cm2RmExe}" -f "${_share_file}.old"; then
    _cm2WarnStrFn "Could not remove ${_share_file}.old";
  fi

  if [ -z "${_lspci_exe}" ]; then
    _cm2ErrStrFn "${_lspci_exe} not found";
    _cm2ErrFn;
  fi

  if [ -z "${_update_exe}" ]; then
    _cm2ErrStrFn "${_update_exe} not found";
    _cm2ErrFn;
  fi

  if "${_update_exe}"; then
    _cm2SucStrFn 'Updated pciids';
    _cm2SucFn;
  else
    _cm2ErrFn;
  fi
}
## . END _updatePciidsFn }

## BEGIN _runTestFn {
declare _rootDir;
_rootDir='';

_runTestFn () {
  declare _fn_str;
  
  # See this hack to execute lib + function as root
  # https://stackoverflow.com/questions/7427262
  IFS='' read -rd '' _fn_str <"${_t00BinDir}/common.2.source";
  _fn_str+="$(declare -f _updatePciidsFn)";
  
  sudo bash -c "${_fn_str}
  _updatePciidsFn";
  return;
}
## . END _runTestFn }
