#!/bin/bash
#
# Purpose: Check kfocus-kclean
# Used by: package-main
#
# set -u is set in _runUnitTests (the test harness)
#
# Script for generating a list of kernel package names (purposefully not
# called in code here):
_makeMockKernelListFn () {
  declare _apt_list_str _image_list _vers_str;
  _apt_list_str="$(apt list |cut -d/ -f1)";

  readarray -t _image_list < <(
    grep -P '^linux-image-[0-9\.-]+' <<<"${_apt_list_str}" \
    | tail -n15 | sed 's/^linux-image-//g'
  );

  for _vers_str in "${_image_list[@]}"; do
    grep -P "^linux-(tools|modules|modules-extra|headers|image)-${_vers_str}" <<< "${_apt_list_str}";
  done
}

## BEGIN _testDataTable
# Values are delimited by ';'.
#   0. Test description
#   1. Flags for running _mainFn
#   2. Answers for cm2PromptUserFn
#   3. Value for (uname -r)
#   4. Value for _echoIsBootMountPointFn
#   5. Values for _echoBootMegsFn 'avail,size'
#   6. Return Int for _cm2RunLongCmdFn
#   7. Value for _echoAptListStrFn

_testDataTable=(
  '.001 Installed Kernels are generic-hwe-22.04-kfocus
  version 6.5.0-14-generic and prior version 6.2.0-35-generic.
- Running kernel is 6.5.0-14-generic.
- /boot is its own partition with 139M free of 705M.
- Results in no action BECAUSE
 -- kclean protects a minimum of 2 kernels.
 -- HOWEVER, a warning for low disk should be shown.
;;y;6.5.0-14-generic;y;139,705;0;
linux-base
linux-firmware
linux-generic-hwe-22.04-kfocus
linux-headers-6.2.0-35-generic
linux-headers-6.5.0-14-generic
linux-headers-generic-hwe-22.04-kfocus
linux-hwe-6.2-headers-6.2.0-35
linux-hwe-6.2-tools-6.2.0-35
linux-hwe-6.5-headers-6.5.0-14
linux-hwe-6.5-tools-6.5.0-14
linux-image-6.2.0-35-generic
linux-image-6.5.0-14-generic
linux-image-generic-hwe-22.04-kfocus
linux-libc-dev
linux-modules-6.2.0-35-generic
linux-modules-6.5.0-14-generic
linux-modules-extra-6.2.0-35-generic
linux-modules-extra-6.5.0-14-generic
linux-sound-base
linux-tools-6.2.0-35-generic
linux-tools-6.5.0-14-generic
linux-tools-common
linux-tools-generic-hwe-22.04-kfocus'

  '.002 Installed Kernels are generic-hwe-22.04-kfocus,
  6.2.0-35-generic and prior version 6.2.0-21-generic.
- Running kernel is 6.5.0-14-generic.
- /boot is its own partition with 139,705 (avail,size).
- Check forced by limited disk space.
- Results in purge of 6.2.0-21-generic.
;;y;6.5.0-14-generic;y;139,705;0;
linux-base
linux-firmware
linux-generic-hwe-22.04-kfocus
linux-headers-6.2.0-35-generic
linux-headers-6.2.0-21-generic
linux-headers-6.5.0-14-generic
linux-headers-generic-hwe-22.04-kfocus
linux-hwe-6.2-headers-6.2.0-35
linux-hwe-6.2-headers-6.2.0-21
linux-hwe-6.2-tools-6.2.0-35
linux-hwe-6.2-tools-6.2.0-21
linux-hwe-6.5-headers-6.5.0-14
linux-hwe-6.5-tools-6.5.0-14
linux-image-6.2.0-35-generic
linux-image-6.2.0-21-generic
linux-image-6.5.0-14-generic
linux-image-generic-hwe-22.04-kfocus
linux-libc-dev
linux-modules-6.2.0-35-generic
linux-modules-6.2.0-21-generic
linux-modules-6.5.0-14-generic
linux-modules-extra-6.2.0-35-generic
linux-modules-extra-6.2.0-21-generic
linux-modules-extra-6.5.0-14-generic
linux-sound-base
linux-tools-6.2.0-35-generic
linux-tools-6.2.0-21-generic
linux-tools-6.5.0-14-generic
linux-tools-common
linux-tools-generic-hwe-22.04-kfocus'

  '.003 Installed Kernels are generic-hwe-22.04-kfocus and 6.2.0-35-generic.
- Running kernel is generic-hwe-22.04-kfocus (6.5.0-14-generic).
- /boot is its own partition with 297M free.
- Results in no action.
;;y;6.5.0-14-generic;y;297,705;0;
linux-base
linux-firmware
linux-generic-hwe-22.04-kfocus
linux-headers-6.2.0-35-generic
linux-headers-6.5.0-14-generic
linux-headers-generic-hwe-22.04-kfocus
linux-hwe-6.2-headers-6.2.0-35
linux-hwe-6.2-tools-6.2.0-35
linux-hwe-6.5-headers-6.5.0-14
linux-hwe-6.5-tools-6.5.0-14
linux-image-6.2.0-35-generic
linux-image-6.5.0-14-generic
linux-image-generic-hwe-22.04-kfocus
linux-libc-dev
linux-modules-6.2.0-35-generic
linux-modules-6.5.0-14-generic
linux-modules-extra-6.2.0-35-generic
linux-modules-extra-6.5.0-14-generic
linux-sound-base
linux-tools-6.2.0-35-generic
linux-tools-6.5.0-14-generic
linux-tools-common
linux-tools-generic-hwe-22.04-kfocus
'

  '.004 Installed kernels are generic-hwe-22.04-kfocus and 6.2.0-35-generic.
- Running kernel is generic-hwe-22.04.
- /boot is its own partition with 297M free.
- Run is forced by -f flag.
- Results in no action BECAUSE:
 -- kclean protects a minimum of two kernsl.
 -- HOWEVER, report is presented due to force flag.
;-f;y;6.5.0-14-generic;y;297,705;0;
linux-base
linux-firmware
linux-generic-hwe-22.04-kfocus
linux-headers-6.2.0-35-generic
linux-headers-6.5.0-14-generic
linux-headers-generic-hwe-22.04-kfocus
linux-hwe-6.2-headers-6.2.0-35
linux-hwe-6.2-tools-6.2.0-35
linux-hwe-6.5-headers-6.5.0-14
linux-hwe-6.5-tools-6.5.0-14
linux-image-6.2.0-35-generic
linux-image-6.5.0-14-generic
linux-image-generic-hwe-22.04-kfocus
linux-libc-dev
linux-modules-6.2.0-35-generic
linux-modules-6.5.0-14-generic
linux-modules-extra-6.2.0-35-generic
linux-modules-extra-6.5.0-14-generic
linux-sound-base
linux-tools-6.2.0-35-generic
linux-tools-6.5.0-14-generic
linux-tools-common
linux-tools-generic-hwe-22.04-kfocus
'

  '.005 Installed kernels are generic-hwe-22.04-kfocus,
  lowlatency-hwe-22.04, and 6.2.0-35-generic.
- Running kernel is lowlatency-hwe-22.04 (6.5.0-21-lowlatency).
- /boot is its own partition with 133M free.
- Results in the removal of 6.2.0-35-generic.
;;y;6.5.0-21-lowlatency;y;133,705;0;
linux-base
linux-firmware
linux-generic-hwe-22.04-kfocus
linux-headers-6.2.0-35-generic
linux-headers-6.5.0-14-generic
linux-headers-6.5.0-21-lowlatency
linux-headers-generic-hwe-22.04-kfocus
linux-hwe-6.2-headers-6.2.0-35
linux-hwe-6.2-tools-6.2.0-35
linux-hwe-6.5-headers-6.5.0-14
linux-hwe-6.5-tools-6.5.0-14
linux-image-6.2.0-35-generic
linux-image-6.5.0-14-generic
linux-image-6.5.0-21-lowlatency
linux-image-generic-hwe-22.04-kfocus
linux-libc-dev
linux-modules-6.2.0-35-generic
linux-modules-6.5.0-14-generic
linux-modules-6.5.0-21-lowlatency
linux-modules-extra-6.2.0-35-generic
linux-modules-extra-6.5.0-14-generic
linux-modules-extra-6.5.0-21-lowlatency
linux-sound-base
linux-tools-6.2.0-35-generic
linux-tools-6.5.0-14-generic
linux-tools-6.5.0-21-lowlatency
linux-tools-common
linux-tools-generic-hwe-22.04-kfocus
'

  '.006 Installed kernels are generic-hwe-22.04-kfocus, generic-hwe-22.04,
  6.5.0-17-generic, and 6.2.0-35-generic.
- Running kernel is generic-hwe-22.04-kfocus (6.5.0-14-generic).
- /boot is its own partition with 0M free.
- Results in purge for 6.5.0-17-generic and 6.2.0-35-generic.
;;y;6.5.0-14-generic;y;0,705;0;
linux-base
linux-firmware
linux-generic-hwe-22.04-kfocus
linux-generix-hwe-22.04
linux-headers-6.2.0-35-generic
linux-headers-6.5.0-14-generic
linux-headers-6.5.0-17-generic
linux-headers-6.5.0-21-generic
linux-headers-generic-hwe-22.04-kfocus
linux-headers-generic-hwe-22.04
linux-hwe-6.2-headers-6.2.0-35
linux-hwe-6.2-tools-6.2.0-35
linux-hwe-6.5-headers-6.5.0-14
linux-hwe-6.5-tools-6.5.0-14
linux-image-6.2.0-35-generic
linux-image-6.5.0-14-generic
linux-image-6.5.0-17-generic
linux-image-6.5.0-21-generic
linux-image-generic-hwe-22.04-kfocus
linux-image-generic-hwe-22.04
linux-libc-dev
linux-modules-6.2.0-35-generic
linux-modules-6.5.0-14-generic
linux-modules-6.5.0-17-generic
linux-modules-6.5.0-21-generic
linux-modules-extra-6.2.0-35-generic
linux-modules-extra-6.5.0-14-generic
linux-modules-extra-6.5.0-17-generic
linux-modules-extra-6.5.0-21-generic
linux-sound-base
linux-tools-6.2.0-35-generic
linux-tools-6.5.0-14-generic
linux-tools-6.5.0-17-generic
linux-tools-6.5.0-21-generic
linux-modules-extra-6.5.0-21-generic
linux-tools-common
linux-tools-generic-hwe-22.04-kfocus
linux-tools-generic-hwe-22.04
'

  '.007 Installed kernels are generic-hwe-22.04-kfocus,
  6.2.0-35-generic, and 5.19.0-50-generic.
- Running kernel is generic-hwe-22.04-kfocus (6.5.0-14-generic).
- /boot is its own partition with 139M free.
- Results in purge of 5.19.0-50-generic.
;;y;6.5.0-14-generic;y;139,705;0;
linux-base
linux-firmware
linux-generic-hwe-22.04-kfocus
linux-headers-6.2.0-35-generic
linux-headers-6.5.0-14-generic
linux-headers-5.19.0-50-generic
linux-headers-generic-hwe-22.04-kfocus
linux-hwe-6.2-headers-6.2.0-35
linux-hwe-6.2-tools-6.2.0-35
linux-hwe-6.5-headers-6.5.0-14
linux-hwe-6.5-tools-6.5.0-14
linux-image-6.2.0-35-generic
linux-image-6.5.0-14-generic
linux-image-5.19.0-50-generic
linux-image-generic-hwe-22.04-kfocus
linux-libc-dev
linux-modules-6.2.0-35-generic
linux-modules-6.5.0-14-generic
linux-modules-5.19.0-50-generic
linux-modules-extra-6.2.0-35-generic
linux-modules-extra-6.5.0-14-generic
linux-modules-extra-5.19.0-50-generic
linux-sound-base
linux-tools-6.2.0-35-generic
linux-tools-6.5.0-14-generic
linux-tools-5.19.0-50-generic
linux-tools-common
linux-tools-generic-hwe-22.04-kfocus
'

  '.008 Installed kernels are generic-hwe-22.04-kfocus (meta purged),
  6.5.0-17-generic, and generic-hwe-22.04.
- /boot is its own partition with 139M free.
- Running kernel is generic-hwe-22.04 (6.5.0-21-generic).
- Results in purge of components of generic-hwe-22.04-kfocus because meta
  purged. These have the version 6.5.0-14-generic.
;;y;6.5.0-21-generic;y;139,705;0;
linux-base
linux-firmware
linux-generic-hwe-22.04
linux-headers-6.5.0-14-generic
linux-headers-6.5.0-17-generic
linux-headers-6.5.0-21-generic
linux-headers-generic-hwe-22.04
linux-hwe-6.5-headers-6.5.0-14
linux-hwe-6.5-tools-6.5.0-14
linux-image-6.5.0-14-generic
linux-image-6.5.0-17-generic
linux-image-6.5.0-21-generic
linux-image-generic-hwe-22.04
linux-libc-dev
linux-modules-6.5.0-14-generic
linux-modules-6.5.0-17-generic
linux-modules-6.5.0-21-generic
linux-modules-extra-6.5.0-14-generic
linux-modules-extra-6.5.0-17-generic
linux-modules-extra-6.5.0-21-generic
linux-sound-base
linux-tools-6.5.0-14-generic
linux-tools-6.5.0-17-generic
linux-tools-6.5.0-21-generic
linux-tools-common
linux-tools-generic-hwe-22.04
'

  '.009 Installed kernels are generic-hwe-22.04-kfocus (meta purged),
  6.5.0-17-generic, and generic-hwe-22.04.
- Running kernel is generic-hwe-22.04 (6.5.0-21-generic).
- /boot is its own partition with 1482M free.
- Results in no action BECAUSE:
 -- Enough disk space is present to permit more than eight kernels to be
    installed.
;;y;6.5.0-21-generic;y;1482,2048;0;
linux-base
linux-firmware
linux-generic-hwe-22.04
linux-headers-6.5.0-14-generic
linux-headers-6.5.0-17-generic
linux-headers-6.5.0-21-generic
linux-headers-generic-hwe-22.04
linux-hwe-6.5-headers-6.5.0-14
linux-hwe-6.5-tools-6.5.0-14
linux-image-6.5.0-14-generic
linux-image-6.5.0-17-generic
linux-image-6.5.0-21-generic
linux-image-generic-hwe-22.04
linux-libc-dev
linux-modules-6.5.0-14-generic
linux-modules-6.5.0-17-generic
linux-modules-6.5.0-21-generic
linux-modules-extra-6.5.0-14-generic
linux-modules-extra-6.5.0-17-generic
linux-modules-extra-6.5.0-21-generic
linux-sound-base
linux-tools-6.5.0-14-generic
linux-tools-6.5.0-17-generic
linux-tools-6.5.0-21-generic
linux-tools-common
linux-tools-generic-hwe-22.04
'

  '.010 Installed kernels are generic-hwe-22.04-kfocus (meta purged),
  6.5.0-17-generic, and generic-hwe-22.04.
- Running kernel is generic-hwe-22.04 (6.5.0-21-generic).
- /boot is on root disk with 1482M free.
- Results in purge of generic-hwe-22.04-kfocus components (6.5.0-14-generic)
  BECAUSE:
 -- Free space is under 10GB, leaving effective space for only two kernels.
;;y;6.5.0-21-generic;n;1482,2048;0;
linux-base
linux-firmware
linux-generic-hwe-22.04
linux-headers-6.5.0-14-generic
linux-headers-6.5.0-17-generic
linux-headers-6.5.0-21-generic
linux-headers-generic-hwe-22.04
linux-hwe-6.5-headers-6.5.0-14
linux-hwe-6.5-tools-6.5.0-14
linux-image-6.5.0-14-generic
linux-image-6.5.0-17-generic
linux-image-6.5.0-21-generic
linux-image-generic-hwe-22.04
linux-libc-dev
linux-modules-6.5.0-14-generic
linux-modules-6.5.0-17-generic
linux-modules-6.5.0-21-generic
linux-modules-extra-6.5.0-14-generic
linux-modules-extra-6.5.0-17-generic
linux-modules-extra-6.5.0-21-generic
linux-sound-base
linux-tools-6.5.0-14-generic
linux-tools-6.5.0-17-generic
linux-tools-6.5.0-21-generic
linux-tools-common
linux-tools-generic-hwe-22.04
'

  '.011 Installed kernels are generic-hwe-22.04-kfocus (meta purged),
  6.5.0-17-generic, and generic-hwe-22.04.
- Running kernel is generic-hwe-22.04 (6.5.0-21-generic).
- /boot is on root disk with 1482M free.
- Run is forced by -f flag.
- Results in purge of generic-hwe-22.04-kfocus components (6.5.0-14-generic)
  BECAUSE:
 -- Free space is under 10GB, leaving effective space for only two kernels.
 -- IN ADDITION, report is presented due to force flag.
;-f;y;6.5.0-21-generic;n;1482,2048;0;
linux-base
linux-firmware
linux-generic-hwe-22.04
linux-headers-6.5.0-14-generic
linux-headers-6.5.0-17-generic
linux-headers-6.5.0-21-generic
linux-headers-generic-hwe-22.04
linux-hwe-6.5-headers-6.5.0-14
linux-hwe-6.5-tools-6.5.0-14
linux-image-6.5.0-14-generic
linux-image-6.5.0-17-generic
linux-image-6.5.0-21-generic
linux-image-generic-hwe-22.04
linux-libc-dev
linux-modules-6.5.0-14-generic
linux-modules-6.5.0-17-generic
linux-modules-6.5.0-21-generic
linux-modules-extra-6.5.0-14-generic
linux-modules-extra-6.5.0-17-generic
linux-modules-extra-6.5.0-21-generic
linux-sound-base
linux-tools-6.5.0-14-generic
linux-tools-6.5.0-17-generic
linux-tools-6.5.0-21-generic
linux-tools-common
linux-tools-generic-hwe-22.04
'

  '.012 Installed kernels are generic-hwe-22.04-kfocus,
  6.5.0-17-generic, and generic-hwe-22.04.
- Running kernel is generic-hwe-22.04 (6.5.0-21-generic).
- /boot is on root disk with 1482M free.
- Run is forced by -f flag.
- Results in purge of 6.5.0-17-generic BECAUSE:
 -- Free space is under 10GB, leaving effective space for only two kernels.
 -- IN ADDITION, report is presented due to force flag.
;-f;y;6.5.0-21-generic;n;1482,2048;0;
linux-base
linux-firmware
linux-generic-hwe-22.04
linux-generic-hwe-22.04-kfocus
linux-headers-6.5.0-14-generic
linux-headers-6.5.0-17-generic
linux-headers-6.5.0-21-generic
linux-headers-generic-hwe-22.04
linux-headers-generic-hwe-22.04-kfocus
linux-hwe-6.5-headers-6.5.0-14
linux-hwe-6.5-tools-6.5.0-14
linux-image-6.5.0-14-generic
linux-image-6.5.0-17-generic
linux-image-6.5.0-21-generic
linux-image-generic-hwe-22.04
linux-image-generic-hwe-22.04-kfocus
linux-libc-dev
linux-modules-6.5.0-14-generic
linux-modules-6.5.0-17-generic
linux-modules-6.5.0-21-generic
linux-modules-extra-6.5.0-14-generic
linux-modules-extra-6.5.0-17-generic
linux-modules-extra-6.5.0-21-generic
linux-sound-base
linux-tools-6.5.0-14-generic
linux-tools-6.5.0-17-generic
linux-tools-6.5.0-21-generic
linux-tools-common
linux-tools-generic-hwe-22.04
linux-tools-generic-hwe-22.04-kfocus
'

  '.013 Installed kernels are generic-hwe-22.04-kfocus,
  6.5.0-17-generic, and generic-hwe-22.04.
- Running kernel is generic-hwe-22.04 (6.5.0-21-generic).
- /boot is on root disk with 101482M free.
- Run is forced by -f flag.
- Results in no action BECAUSE:
 -- Free space exceeds 5 * kernel unit size int (200MB).
 -- Enough disk space is present to permit more than 8 kernels to be
    installed.
 -- HOWEVER, report is presented due to force flag.
;-f;y;6.5.0-21-generic;n;101482,102048;0;
linux-base
linux-firmware
linux-generic-hwe-22.04
linux-generic-hwe-22.04-kfocus
linux-headers-6.5.0-14-generic
linux-headers-6.5.0-17-generic
linux-headers-6.5.0-21-generic
linux-headers-generic-hwe-22.04
linux-headers-generic-hwe-22.04-kfocus
linux-hwe-6.5-headers-6.5.0-14
linux-hwe-6.5-tools-6.5.0-14
linux-image-6.5.0-14-generic
linux-image-6.5.0-17-generic
linux-image-6.5.0-21-generic
linux-image-generic-hwe-22.04
linux-image-generic-hwe-22.04-kfocus
linux-libc-dev
linux-modules-6.5.0-14-generic
linux-modules-6.5.0-17-generic
linux-modules-6.5.0-21-generic
linux-modules-extra-6.5.0-14-generic
linux-modules-extra-6.5.0-17-generic
linux-modules-extra-6.5.0-21-generic
linux-sound-base
linux-tools-6.5.0-14-generic
linux-tools-6.5.0-17-generic
linux-tools-6.5.0-21-generic
linux-tools-common
linux-tools-generic-hwe-22.04
linux-tools-generic-hwe-22.04-kfocus
'

  '.014 Installed kernels are generic-hwe-22.04-kfocus, 6.2.0-35-generic,
  5.19.0-50-generic, and 5.15.0-97-generic.
- Running kernel is 5.15.0-97-generic.
- /boot is its own partition with 0M free.
- Results in purge for 6.2.0-35-generic and 5.19.0-50-generic.
;;y;5.15.0-97-generic;y;0,500;0;
linux-base
linux-firmware
linux-generic-hwe-22.04-kfocus
linux-headers-6.2.0-35-generic
linux-headers-6.5.0-14-generic
linux-headers-5.19.0-50-generic
linux-headers-5.15.0-97-generic
linux-headers-generic-hwe-22.04-kfocus
linux-hwe-6.2-headers-6.2.0-35
linux-hwe-6.2-tools-6.2.0-35
linux-hwe-6.5-headers-6.5.0-14
linux-hwe-6.5-tools-6.5.0-14
linux-image-6.2.0-35-generic
linux-image-6.5.0-14-generic
linux-image-5.19.0-50-generic
linux-image-5.15.0-97-generic
linux-image-generic-hwe-22.04-kfocus
linux-libc-dev
linux-modules-6.2.0-35-generic
linux-modules-6.5.0-14-generic
linux-modules-5.19.0-50-generic
linux-modules-5.15.0-97-generic
linux-modules-extra-6.2.0-35-generic
linux-modules-extra-6.5.0-14-generic
linux-modules-extra-5.19.0-50-generic
linux-modules-extra-5.15.0-97-generic
linux-sound-base
linux-tools-6.2.0-35-generic
linux-tools-6.5.0-14-generic
linux-tools-5.19.0-50-generic
linux-tools-5.15.0-97-generic
linux-tools-common
linux-tools-generic-hwe-22.04-kfocus
'

  '.015 Installed Kernels 15 6.5.0 kernel variants.
- Running kernel is 6.5.0-14-generic.
- /boot is on root disk. Sizes are 11610,16460 (avail,size).
- Check forced: > 8 kernels found.
;;y;6.5.0-14-generic;n;11610,16460;0;
linux-base
linux-firmware
linux-headers-generic-hwe-22.04-kfocus
linux-image-generic-hwe-22.04-kfocus
linux-libc-dev
linux-sound-base
linux-headers-6.5.0-1014-gcp
linux-image-6.5.0-1014-gcp
linux-modules-6.5.0-1014-gcp
linux-modules-extra-6.5.0-1014-gcp
linux-tools-6.5.0-1014-gcp
linux-headers-6.5.0-1014-oem
linux-image-6.5.0-1014-oem
linux-modules-6.5.0-1014-oem
linux-tools-6.5.0-1014-oem
linux-headers-6.5.0-1014-oracle
linux-image-6.5.0-1014-oracle
linux-modules-6.5.0-1014-oracle
linux-modules-extra-6.5.0-1014-oracle
linux-tools-6.5.0-1014-oracle
linux-image-6.5.0-1015-azure-fde
linux-headers-6.5.0-1015-azure
linux-image-6.5.0-1015-azure-fde
linux-image-6.5.0-1015-azure
linux-modules-6.5.0-1015-azure
linux-modules-extra-6.5.0-1015-azure
linux-tools-6.5.0-1015-azure
linux-headers-6.5.0-1015-oracle
linux-image-6.5.0-1015-oracle
linux-modules-6.5.0-1015-oracle
linux-modules-extra-6.5.0-1015-oracle
linux-tools-6.5.0-1015-oracle
linux-headers-6.5.0-1016-oracle
linux-image-6.5.0-1016-oracle
linux-modules-6.5.0-1016-oracle
linux-modules-extra-6.5.0-1016-oracle
linux-tools-6.5.0-1016-oracle
linux-headers-6.5.0-14-generic
linux-image-6.5.0-14-generic
linux-modules-6.5.0-14-generic
linux-modules-extra-6.5.0-14-generic
linux-tools-6.5.0-14-generic
linux-headers-6.5.0-14-lowlatency
linux-image-6.5.0-14-lowlatency
linux-modules-6.5.0-14-lowlatency
linux-tools-6.5.0-14-lowlatency
linux-headers-6.5.0-15-generic
linux-image-6.5.0-15-generic
linux-modules-6.5.0-15-generic
linux-modules-extra-6.5.0-15-generic
linux-tools-6.5.0-15-generic
linux-headers-6.5.0-15-lowlatency
linux-image-6.5.0-15-lowlatency
linux-modules-6.5.0-15-lowlatency
linux-tools-6.5.0-15-lowlatency
linux-headers-6.5.0-17-generic
linux-image-6.5.0-17-generic
linux-modules-6.5.0-17-generic
linux-modules-extra-6.5.0-17-generic
linux-tools-6.5.0-17-generic
linux-headers-6.5.0-17-lowlatency
linux-image-6.5.0-17-lowlatency
linux-modules-6.5.0-17-lowlatency
linux-tools-6.5.0-17-lowlatency
linux-headers-6.5.0-18-generic
linux-image-6.5.0-18-generic
linux-modules-6.5.0-18-generic
linux-modules-extra-6.5.0-18-generic
linux-tools-6.5.0-18-generic
linux-headers-6.5.0-21-generic
linux-image-6.5.0-21-generic
linux-modules-6.5.0-21-generic
linux-modules-extra-6.5.0-21-generic
linux-tools-6.5.0-21-generic'

  '.016 Installed kernels are generic-hwe-22.04-kfocus,
  6.5.0-17-generic, and generic-hwe-22.04.
- Running kernel is generic-hwe-22.04 (6.5.0-21-generic).
- /boot is on large root disk with 500M free.
- Run is forced by -f flag.
- Results in purge of 6.5.0-17-generic BECAUSE:
 -- Free space does NOT exceed 5 * kernel unit size int (200MB).
;;y;6.5.0-21-generic;n;500,102048;0;
linux-base
linux-firmware
linux-generic-hwe-22.04
linux-generic-hwe-22.04-kfocus
linux-headers-6.5.0-14-generic
linux-headers-6.5.0-17-generic
linux-headers-6.5.0-21-generic
linux-headers-generic-hwe-22.04
linux-headers-generic-hwe-22.04-kfocus
linux-hwe-6.5-headers-6.5.0-14
linux-hwe-6.5-tools-6.5.0-14
linux-image-6.5.0-14-generic
linux-image-6.5.0-17-generic
linux-image-6.5.0-21-generic
linux-image-generic-hwe-22.04
linux-image-generic-hwe-22.04-kfocus
linux-libc-dev
linux-modules-6.5.0-14-generic
linux-modules-6.5.0-17-generic
linux-modules-6.5.0-21-generic
linux-modules-extra-6.5.0-14-generic
linux-modules-extra-6.5.0-17-generic
linux-modules-extra-6.5.0-21-generic
linux-sound-base
linux-tools-6.5.0-14-generic
linux-tools-6.5.0-17-generic
linux-tools-6.5.0-21-generic
linux-tools-common
linux-tools-generic-hwe-22.04
linux-tools-generic-hwe-22.04-kfocus
'
);
## . END _testDataTable

## BEGIN _overwriteWithMocksFn {
# Purpose: Overwrite functions from sourced script before running tests
_overwriteWithMocksFn () {
  # 1. _cm2PromptUserFn
  # shellcheck disable=SC2317
  _cm2PromptUserFn () {
    declare _prompt_str _query_type _ans_str;
    _prompt_str="${1:-Continue}";
    _query_type="${3:-}";
    _ans_str="${_testAnsList[$_testAnsIdx]}";

    case "${_query_type}" in
      [aw]) _prompt_str="$(_cm2StripTagsFn "${_prompt_str}" 'n')";;
      p) _prompt_str="$(_cm2StripTagsFn "${_prompt_str}" 'y')";
         _prompt_str+="\n\nPress <return> to continue.";;
      *) _prompt_str="$(_cm2StripTagsFn "${_prompt_str}" 'n')";;
    esac
    echo -e "${_prompt_str}" >> "${_runFile}";
    if [[ "${_query_type}" =~ [aw] ]]; then
      echo -e "${_ans_str}" >> "${_runFile}";
    fi
  }

  # 2. (uname -r) for _echoKversRunStrFn and _echoKversFullRunStrFn
  # shellcheck disable=SC2317
  function uname () { echo "${_testDataList[3]}"; }
  # 3. _echoIsBootMountPointFn
  # shellcheck disable=SC2317
  _echoIsBootMountPointFn () { echo "${_testDataList[4]}"; }
  # 4. _echoBootMegsFn (used twice, 'size' and 'avail')
  # shellcheck disable=SC2317
  _echoBootMegsFn () {
    declare _idx=1
    [ "${1:-}" = 'size' ] && _idx=2;
    cut -f"${_idx}" -d, <<<"${_testDataList[5]}";
  }
  # 5. _cm2RunLongCmdFn (return) - this runs the purge
  # shellcheck disable=SC2317
  _cm2RunLongCmdFn () {
    echo -e "\nPurge Package List:\n${*:-}\n" >>"${_runFile}";
    return "${_testDataList[6]}";
  }
  # 7. _echoAptListStrFn
  # shellcheck disable=SC2317
  _echoAptListStrFn () { echo "${_testDataList[7]}"; }

  # shellcheck disable=SC2317
  _echoMetaKversStrFn () {
    if [[ "${_aptListStr}" =~ ${1:-} ]]; then
      case "${1:-}" in
      'linux-image-generic-hwe-22.04-kfocus' ) echo '6.5.0-14-generic' ;;
      'linux-image-lowlatency-hwe-22.04'     ) echo '6.5.0-18-lowlatency' ;;
      esac
    else
      echo 'XXX_NOT_INSTALLED_XXX';
    fi
  }
}
## . END _overwriteWithMocksFn }

## BEGIN _unsetMocksFn {
# Purpose : Unset mocked functions and other globals to prevent
#   pollution of namespaces. Mocked functions from commons.2.source are not
#   reset here; instead they are re-source after every test in runUnitTests
#   (the test harness).
#
# If we ever do need to reset a function, this can work, but avoid this
#   technique oin production scripts due to eval:
# _priorCm2PromptUserStr="$(declare -f _cm2PromptUserFn)";
# eval "${_priorCm2PromptUserStr}"; # Restore above function.
#
_unsetMocksFn () {
  # 1. _cm2PromptUserFn
  # 2. (uname -r) for _echoBootInfoStr
  # 3. _echoIsBootMountPointFn
  # 4. _echoBootMegsFn
  # 5. _cm2RunLongCmdFn (return)
  # 6. _echoAptListStrFn
  unset _cm2PromptUserFn uname _echoIsBootMountPointFn _echoBootMegsFn \
    _cm2RunLongCmdFn _attemptInstallRepairFn _echoAptListStrFn \
    _testDataList _testAnsList testAnsIdx _runFile;
}
## . END _unsetMocksFn }

## BEGIN _runTestFn {
# This MUST be called '_runTestFn' for use by the _runUnitTests
# bashsupport disable=BP2001
_runTestFn () {
  declare _exe_file _fail_count _test_count _test_idx _test_line_str \
    _arg_list _expect_file _check_str;

  # Use function from _runUnitTests: clear out run dir and check expect dir
  if ! _t00ClearRunDirFn;    then return 1; fi
  if ! _t00CheckExpectDirFn; then return 1; fi

  # bashsupport disable=BP2001
  # shellcheck disable=SC2154,SC2034
  _exe_file="${_t00TopDir}";
  _exe_file+='/package-main/usr/lib/kfocus/bin/kfocus-kclean';

  # Test for CLI version
  # _exe_file+='/r+d/tools/kfocus-kclean-cli';

  # shellcheck disable=SC1090,SC2154
  source "${_exe_file}" || exit 1;

  # Set environment vars
  export XDG_SESSION_TYPE='tty';

  # The test harness imports _cm2 routines.

  # Overwrite functions with mocks
  _overwriteWithMocksFn;

  ## Begin Iterate through tests {
  _fail_count=0;
  _test_count="${#_testDataTable[@]}";
  _test_idx=1;
  for _test_line_str in "${_testDataTable[@]}"; do
    _cm2EchoFn "BEGIN Test ${_test_idx} of ${_test_count}:";

    # Extract _dataList, _ansList, and reset _testAnsIdx
    IFS=';' read -r -d '' -a _testDataList< <(echo -n "${_test_line_str}");
    IFS=' ' read -r -d '' -a _arg_list    < <(echo -n "${_testDataList[1]}");
    IFS=',' read -r -d '' -a _testAnsList < <(echo -n "${_testDataList[2]}");
    _testAnsIdx=0;

    # Calculate expect and run files
    # shellcheck disable=SC2154
    _expect_file="$(
      printf '%s/test_%02d.txt' "${_t00ExpectDir}" "${_test_idx}"
    )";
    # shellcheck disable=SC2154
    _runFile="$(printf '%s/test_%02d.txt' "${_t00RunDir}" "${_test_idx}")";
    # Start file with description
    echo -e "${_testDataList[0]}" >"${_runFile}";

    # Run _mainFn from fixup_kernels with args using mocked functions
    # Reset getopts to work per
    # https://unix.stackexchange.com/questions/233728
    export OPTIND=1;
    _mainFn "${_arg_list[@]}";

    ## Begin Check diffs {
    if [ ! -f "${_expect_file}" ]; then touch "${_expect_file}"; fi
    _check_str="$(diff -r --brief "${_expect_file}" "${_runFile}" )";
    if [ -z "${_check_str}" ]; then
      _cm2EchoFn ". OK   test ${_test_idx}\n\n";
    else
      _cm2EchoFn 'Please compare expected to run file';
      meld "${_expect_file}" "${_runFile}";
      _cm2EchoFn ". FAIL test ${_test_idx}\n\n";
      (( _fail_count++ ));
    fi
    ## . End Check diffs }
    (( _test_idx++ ));
  done
  ## End Iterate through tests }

  if [ "${_fail_count}" -gt 0 ]; then
    _cm2EchoFn "FAIL: ${_fail_count} of ${_test_count} tests failed.";
  else
    _cm2EchoFn 'OK  : Results match expected';
  fi

  # Revert function names
  _unsetMocksFn;

  return "${_fail_count}";
}
## . END _runTestFn }
