#!/bin/bash
#
# Purpose: Check kfocus-kclean
# Used by: package-main
#
# set -u is set in _runUnitTests (the test harness)
#
# Script for generating a list of kernel package names (purposefully not
# called in code here):
_makeMockKernelListFn () {
  declare _apt_list_str _image_list _vers_str;
  _apt_list_str="$(apt list |cut -d/ -f1)";

  readarray -t _image_list < <(
    grep -P '^linux-image-[0-9\.-]+' <<<"${_apt_list_str}" \
    | tail -n15 | sed 's/^linux-image-//g'
  );

  for _vers_str in "${_image_list[@]}"; do
    grep -P "^linux-(tools|modules|modules-extra|headers|image)-${_vers_str}" <<< "${_apt_list_str}";
  done
}

## BEGIN _assertDataTable
# Values are delimited by ';'.
#   0. Test description
#   1. Flags for running _mainFn
#   2. Answers for cm2PromptUserFn
#   3. Value for (uname -r)
#   4. Value for _echoIsBootMountPointFn
#   5. Values for _echoBootMegsFn 'avail,size'
#   6. Return Int for _cm2RunLongCmdFn
#   7. Value for _echoAptListStrFn

_assertDataTable=(
  '_001 Installed kernels are
6.5.0-14-generic (generic-hwe-22.04-kfocus),
6.2.0-35-generic.
- Running kernel is 6.5.0-14-generic per assert.
- Blessed kernel is 6.5.0-14-generic because meta installed per assert.
- /boot is its own partition with 139 free of 705M.
- Check Forced: Low disk space (139 < 230 reserved for kernels)
- Results in NO PURGE because a minimum of 2 kernels is preserved.
 -- HOWEVER, a warning for low disk should be shown.
;;y;6.5.0-14-generic;y;139,705;0;
linux-base
linux-firmware
linux-generic-hwe-22.04-kfocus
linux-headers-6.2.0-35-generic
linux-headers-6.5.0-14-generic
linux-headers-generic-hwe-22.04-kfocus
linux-hwe-6.2-headers-6.2.0-35
linux-hwe-6.2-tools-6.2.0-35
linux-hwe-6.5-headers-6.5.0-14
linux-hwe-6.5-tools-6.5.0-14
linux-image-6.2.0-35-generic
linux-image-6.5.0-14-generic
linux-image-generic-hwe-22.04-kfocus
linux-libc-dev
linux-modules-6.2.0-35-generic
linux-modules-6.5.0-14-generic
linux-modules-extra-6.2.0-35-generic
linux-modules-extra-6.5.0-14-generic
linux-sound-base
linux-tools-6.2.0-35-generic
linux-tools-6.5.0-14-generic
linux-tools-common
linux-tools-generic-hwe-22.04-kfocus'

  '_002 Installed kernels are
6.5.0-14-generic (generic-hwe-22.04-kfocus),
6.2.0-35-generic, 6.2.0-21-generic.
- Running kernel is 6.5.0-14-generic per assert.
- Blessed kernel is 6.5.0-14-generic because meta installed per assert.
- /boot is its own partition with 139 free of 705M.
- Check Forced: Low disk space (139 < 230 reserved for kernels)
- Results in purge of only 6.2.0-21-generic BECAUSE:
-- 6.5.0-14-generic is running and blessed, so retained
-- 6.2.0-35-generic is retained because of the 2-kernel minimum
;;y;6.5.0-14-generic;y;139,705;0;
linux-base
linux-firmware
linux-generic-hwe-22.04-kfocus
linux-headers-6.2.0-35-generic
linux-headers-6.2.0-21-generic
linux-headers-6.5.0-14-generic
linux-headers-generic-hwe-22.04-kfocus
linux-hwe-6.2-headers-6.2.0-35
linux-hwe-6.2-headers-6.2.0-21
linux-hwe-6.2-tools-6.2.0-35
linux-hwe-6.2-tools-6.2.0-21
linux-hwe-6.5-headers-6.5.0-14
linux-hwe-6.5-tools-6.5.0-14
linux-image-6.2.0-35-generic
linux-image-6.2.0-21-generic
linux-image-6.5.0-14-generic
linux-image-generic-hwe-22.04-kfocus
linux-libc-dev
linux-modules-6.2.0-35-generic
linux-modules-6.2.0-21-generic
linux-modules-6.5.0-14-generic
linux-modules-extra-6.2.0-35-generic
linux-modules-extra-6.2.0-21-generic
linux-modules-extra-6.5.0-14-generic
linux-sound-base
linux-tools-6.2.0-35-generic
linux-tools-6.2.0-21-generic
linux-tools-6.5.0-14-generic
linux-tools-common
linux-tools-generic-hwe-22.04-kfocus'

  '_003 Installed kernels are
 6.5.0-14 (generic-hwe-22.04-kfocus), 6.2.0-35-generic.
- Running kernel is 6.5.0-14-generic per assert.
- Blessed kernel is 6.5.0-14-generic because meta installed per assert.
- /boot is its own partition with 297 free of 705M.
- Check NOT Forced: Enough disk space
- Results in no action BECAUSE:
-- There is enough room for one more kernel (297M > 230M)
-- This is NOT low space when total space allows (705/230 = 3) kernels
;;y;6.5.0-14-generic;y;297,705;0;
linux-base
linux-firmware
linux-generic-hwe-22.04-kfocus
linux-headers-6.2.0-35-generic
linux-headers-6.5.0-14-generic
linux-headers-generic-hwe-22.04-kfocus
linux-hwe-6.2-headers-6.2.0-35
linux-hwe-6.2-tools-6.2.0-35
linux-hwe-6.5-headers-6.5.0-14
linux-hwe-6.5-tools-6.5.0-14
linux-image-6.2.0-35-generic
linux-image-6.5.0-14-generic
linux-image-generic-hwe-22.04-kfocus
linux-libc-dev
linux-modules-6.2.0-35-generic
linux-modules-6.5.0-14-generic
linux-modules-extra-6.2.0-35-generic
linux-modules-extra-6.5.0-14-generic
linux-sound-base
linux-tools-6.2.0-35-generic
linux-tools-6.5.0-14-generic
linux-tools-common
linux-tools-generic-hwe-22.04-kfocus'

  '_004 Installed Kernels are
6.5.0-14 (generic-hwe-22.04-kfocus), 6.2.0-35-generic.
- Running kernel is 6.5.0-14-generic per assert.
- Blessed kernel is 6.5.0-14-generic because meta installed per assert.
- /boot is its own partition with 297 free of 705M.
- Check Forced: -f flag used.
- Results in no purge offered BECAUSE:
-- There is enough room for one more kernel (297M > 230M)
-- This is NOT low space when total space allows (705/230 = 3) kernels
;-f;y;6.5.0-14-generic;y;297,705;0;
linux-base
linux-firmware
linux-generic-hwe-22.04-kfocus
linux-headers-6.2.0-35-generic
linux-headers-6.5.0-14-generic
linux-headers-generic-hwe-22.04-kfocus
linux-hwe-6.2-headers-6.2.0-35
linux-hwe-6.2-tools-6.2.0-35
linux-hwe-6.5-headers-6.5.0-14
linux-hwe-6.5-tools-6.5.0-14
linux-image-6.2.0-35-generic
linux-image-6.5.0-14-generic
linux-image-generic-hwe-22.04-kfocus
linux-libc-dev
linux-modules-6.2.0-35-generic
linux-modules-6.5.0-14-generic
linux-modules-extra-6.2.0-35-generic
linux-modules-extra-6.5.0-14-generic
linux-sound-base
linux-tools-6.2.0-35-generic
linux-tools-6.5.0-14-generic
linux-tools-common
linux-tools-generic-hwe-22.04-kfocus'

  '_005 Installed kernels are
6.5.0-14-generic (generic-hwe-22.04-kfocus),
6.5.0-21-lowlatency (lowlatency-hwe-22.04),
6.2.0-35-generic.
- Running kernel is 6.5.0-21-lowlatency (lowlatency-hwe-22.04) per assert.
- Blessed kernel is 6.5.0-14-generic because meta installed per assert.
- /boot is its own partition with 133 free of 705M.
- Check Forced: Low disk space
- Results in purge of only 6.2.0-35-generic BECAUSE:
-- 6.5.0-21-lowlatency is running, so retained.
-- 6.2.0-14-generic is blessed, so retained.
-- 6.2.0-35-generic IS PURGED because it is not protected, and...
--- There is NOT enough room for one more kernel (133M < 230M).
--- This is low space when total space only allows (705/230 = 3) kernels.
;;y;6.5.0-21-lowlatency;y;133,705;0;
linux-base
linux-firmware
linux-generic-hwe-22.04-kfocus
linux-headers-6.2.0-35-generic
linux-headers-6.5.0-14-generic
linux-headers-6.5.0-21-lowlatency
linux-headers-generic-hwe-22.04-kfocus
linux-hwe-6.2-headers-6.2.0-35
linux-hwe-6.2-tools-6.2.0-35
linux-hwe-6.5-headers-6.5.0-14
linux-hwe-6.5-headers-6.5.0-21
linux-hwe-6.5-tools-6.5.0-14
linux-hwe-6.5-tools-6.5.0-21
linux-image-6.2.0-35-generic
linux-image-6.5.0-14-generic
linux-image-6.5.0-21-lowlatency
linux-image-generic-hwe-22.04-kfocus
linux-libc-dev
linux-modules-6.2.0-35-generic
linux-modules-6.5.0-14-generic
linux-modules-6.5.0-21-lowlatency
linux-modules-extra-6.2.0-35-generic
linux-modules-extra-6.5.0-14-generic
linux-modules-extra-6.5.0-21-lowlatency
linux-sound-base
linux-tools-6.2.0-35-generic
linux-tools-6.5.0-14-generic
linux-tools-6.5.0-21-lowlatency
linux-tools-common
linux-tools-generic-hwe-22.04-kfocus'

  '_006 Installed kernels are
6.5.0-21-generic (generic-hwe-22.04)
6.5.0-17-generic,
6.5.0-14-generic (generic-hwe-22.04-kfocus),
6.2.0-35-generic,
- Running kernel is 6.5.0-14-generic per assert.
- Blessed kernel is 6.5.0-14-generic because meta installed per assert.
- /boot is its own partition with 0 free of 705M.
- Check Forced: Low disk space
- Results in purge of 6.5.0-21-generic, 6.5.0-17-generic
-- 6.2.0-14-generic is running and blessed, so retained.
-- 6.5.0-21-generic is latest remaining version, kept for 2 minimum.
-- 6.2.0-35-generic IS PURGED because it is not protected
-- 6.5.0-17-generic IS PURGED because it is not protected
--- There is NOT enough room for one more kernel (0 < 230M).
--- This is low space when total space only allows (705/230 = 3) kernels.
;;y;6.5.0-14-generic;y;0,705;0;
linux-base
linux-firmware
linux-generic-hwe-22.04-kfocus
linux-generic-hwe-22.04
linux-headers-6.2.0-35-generic
linux-headers-6.5.0-14-generic
linux-headers-6.5.0-17-generic
linux-headers-6.5.0-21-generic
linux-headers-generic-hwe-22.04-kfocus
linux-headers-generic-hwe-22.04
linux-hwe-6.2-headers-6.2.0-35
linux-hwe-6.2-tools-6.2.0-35
linux-hwe-6.5-headers-6.5.0-14
linux-hwe-6.5-headers-6.5.0-17
linux-hwe-6.5-headers-6.5.0-21
linux-hwe-6.5-tools-6.5.0-14
linux-hwe-6.5-tools-6.5.0-17
linux-hwe-6.5-tools-6.5.0-21
linux-image-6.2.0-35-generic
linux-image-6.5.0-14-generic
linux-image-6.5.0-17-generic
linux-image-6.5.0-21-generic
linux-image-generic-hwe-22.04-kfocus
linux-image-generic-hwe-22.04
linux-libc-dev
linux-modules-6.2.0-35-generic
linux-modules-6.5.0-14-generic
linux-modules-6.5.0-17-generic
linux-modules-6.5.0-21-generic
linux-modules-extra-6.2.0-35-generic
linux-modules-extra-6.5.0-14-generic
linux-modules-extra-6.5.0-17-generic
linux-modules-extra-6.5.0-21-generic
linux-sound-base
linux-tools-6.2.0-35-generic
linux-tools-6.5.0-14-generic
linux-tools-6.5.0-17-generic
linux-tools-6.5.0-21-generic
linux-modules-extra-6.5.0-21-generic
linux-tools-common
linux-tools-generic-hwe-22.04-kfocus
linux-tools-generic-hwe-22.04'

  '_007 Installed kernels are
6.5.0-14-generic (generic-hwe-22.04-kfocus)
6.2.0-35-generic, 5.19.0-50-generic.
- Running kernel is 6.5.0-14-generic per assert.
- Blessed kernel is 6.5.0-14-generic because meta installed per assert.
- /boot is its own partition with 139 free of 705M.
- Check Forced: Low disk space
- Results in purge of 5.19.0-50-generic
-- 6.5.0-14-generic is running and blessed, so retained.
-- 6.2.0-35-generic is next latest remaining version, kept for 2 minimum.
-- 5.19.0-50-generic IS PURGED because it is not protected
--- There is NOT enough room for one more kernel (139 < 230M).
--- This is low space when total space only allows (705/230 = 3) kernels.
- Results in purge of 5.19.0-50-generic.
;;y;6.5.0-14-generic;y;139,705;0;
linux-base
linux-firmware
linux-generic-hwe-22.04-kfocus
linux-headers-6.2.0-35-generic
linux-headers-6.5.0-14-generic
linux-headers-5.19.0-50-generic
linux-headers-generic-hwe-22.04-kfocus
linux-hwe-5.19-headers-5.19.0-50
linux-hwe-5.19-tools-5.19.0-50
linux-hwe-6.2-headers-6.2.0-35
linux-hwe-6.2-tools-6.2.0-35
linux-hwe-6.5-headers-6.5.0-14
linux-hwe-6.5-tools-6.5.0-14
linux-image-6.2.0-35-generic
linux-image-6.5.0-14-generic
linux-image-5.19.0-50-generic
linux-image-generic-hwe-22.04-kfocus
linux-libc-dev
linux-modules-6.2.0-35-generic
linux-modules-6.5.0-14-generic
linux-modules-5.19.0-50-generic
linux-modules-extra-6.2.0-35-generic
linux-modules-extra-6.5.0-14-generic
linux-modules-extra-5.19.0-50-generic
linux-sound-base
linux-tools-6.2.0-35-generic
linux-tools-6.5.0-14-generic
linux-tools-5.19.0-50-generic
linux-tools-common
linux-tools-generic-hwe-22.04-kfocus'

  '_008 Installed kernels are
6.5.0-21-generic (generic-hwe-22.04),
6.5.0-17-generic,
6.5.0-14-generic (generic-hwe-22.04-kfocus) (meta purged).
- Running kernel is 6.5.0-21-generic (generic-hwe-22.04) per assert.
- Blessed kernel is NOT FOUND because meta not installed per assert.
- /boot is its own partition with 139 free of 705M.
- Check Forced: Low disk space
- Results in purge BECAUSE:
-- 6.5.0-21-generic is running, so retained.
-- 6.5.0-17-generic is next version, so retained.
-- 6.5.0-14-generic IS PURGED because it is not blessed
   because the generic-hw-22.04-kfocus is purged.
--- There is NOT enough room for one more kernel (139 < 230M).
--- This is low space when total space only allows (705/230 = 3) kernels.
;;y;6.5.0-21-generic;y;139,705;0;
linux-base
linux-firmware
linux-generic-hwe-22.04
linux-headers-6.5.0-14-generic
linux-headers-6.5.0-17-generic
linux-headers-6.5.0-21-generic
linux-headers-generic-hwe-22.04
linux-hwe-6.5-headers-6.5.0-14
linux-hwe-6.5-headers-6.5.0-17
linux-hwe-6.5-headers-6.5.0-21
linux-hwe-6.5-tools-6.5.0-14
linux-hwe-6.5-tools-6.5.0-17
linux-hwe-6.5-tools-6.5.0-21
linux-image-6.5.0-14-generic
linux-image-6.5.0-17-generic
linux-image-6.5.0-21-generic
linux-image-generic-hwe-22.04
linux-libc-dev
linux-modules-6.5.0-14-generic
linux-modules-6.5.0-17-generic
linux-modules-6.5.0-21-generic
linux-modules-extra-6.5.0-14-generic
linux-modules-extra-6.5.0-17-generic
linux-modules-extra-6.5.0-21-generic
linux-sound-base
linux-tools-6.5.0-14-generic
linux-tools-6.5.0-17-generic
linux-tools-6.5.0-21-generic
linux-tools-common
linux-tools-generic-hwe-22.04'

  '_009 Installed kernels are
6.5.0-21-generic (generic-hwe-22.04),
6.5.0-17-generic,
6.5.0-14-generic (generic-hwe-22.04-kfocus) (meta purged).
- Running kernel is 6.5.0-21-generic (generic-hwe-22.04) per assert.
- Blessed kernel is NOT FOUND because meta not installed per assert.
- /boot is its own partition with 1482 free of 2048M.
- Results in no action BECAUSE:
-- There is enough room for many more kernels (1482 > 230M), around 6x
-- Enough disk space is present to permit 8 kernels to be installed.
-- The target keep number is greater than installed, 5 > 3
;;y;6.5.0-21-generic;y;1482,2048;0;
linux-base
linux-firmware
linux-generic-hwe-22.04
linux-headers-6.5.0-14-generic
linux-headers-6.5.0-17-generic
linux-headers-6.5.0-21-generic
linux-headers-generic-hwe-22.04
linux-hwe-6.5-headers-6.5.0-14
linux-hwe-6.5-headers-6.5.0-17
linux-hwe-6.5-headers-6.5.0-21
linux-hwe-6.5-tools-6.5.0-14
linux-hwe-6.5-tools-6.5.0-17
linux-hwe-6.5-tools-6.5.0-21
linux-image-6.5.0-14-generic
linux-image-6.5.0-17-generic
linux-image-6.5.0-21-generic
linux-image-generic-hwe-22.04
linux-libc-dev
linux-modules-6.5.0-14-generic
linux-modules-6.5.0-17-generic
linux-modules-6.5.0-21-generic
linux-modules-extra-6.5.0-14-generic
linux-modules-extra-6.5.0-17-generic
linux-modules-extra-6.5.0-21-generic
linux-sound-base
linux-tools-6.5.0-14-generic
linux-tools-6.5.0-17-generic
linux-tools-6.5.0-21-generic
linux-tools-common
linux-tools-generic-hwe-22.04'

  '_010 Installed kernels are:
6.5.0-21-generic (generic-hwe-22.04),
6.5.0-17-generic,
6.5.0-14-generic (generic-hwe-22.04-kfocus) (meta purged).
- Running kernel is 6.5.0-21-generic (generic-hwe-22.04) per assert.
- Blessed kernel is NOT FOUND because meta not installed per assert.
- /boot is NOT its own partition with 1482 free of 2048M.
- Results in PURGE
-- 6.5.0-21-generic is running, so retained.
-- 6.5.0-17-generic is next version, so retained.
-- 6.5.0-14-generic is PURGED because it is not bless
--- generic-hwe-22.04-kfocus meta is not in package list.
-- Root disk free space < 10GB, so effective size is 1482/8 = 185
-- Effective free size is free 185-(3*230) = -505
--- There is NOT enough room for one more kernel (-505 < 230M).
--- This is low space when total space only allows (-505/230 = -2) kernels.
;;y;6.5.0-21-generic;n;1482,2048;0;
linux-base
linux-firmware
linux-generic-hwe-22.04
linux-headers-6.5.0-14-generic
linux-headers-6.5.0-17-generic
linux-headers-6.5.0-21-generic
linux-headers-generic-hwe-22.04
linux-hwe-6.5-headers-6.5.0-14
linux-hwe-6.5-headers-6.5.0-17
linux-hwe-6.5-headers-6.5.0-21
linux-hwe-6.5-tools-6.5.0-14
linux-hwe-6.5-tools-6.5.0-17
linux-hwe-6.5-tools-6.5.0-21
linux-image-6.5.0-14-generic
linux-image-6.5.0-17-generic
linux-image-6.5.0-21-generic
linux-image-generic-hwe-22.04
linux-libc-dev
linux-modules-6.5.0-14-generic
linux-modules-6.5.0-17-generic
linux-modules-6.5.0-21-generic
linux-modules-extra-6.5.0-14-generic
linux-modules-extra-6.5.0-17-generic
linux-modules-extra-6.5.0-21-generic
linux-sound-base
linux-tools-6.5.0-14-generic
linux-tools-6.5.0-17-generic
linux-tools-6.5.0-21-generic
linux-tools-common
linux-tools-generic-hwe-22.04'

  '_011 Installed kernels are:
6.5.0-21-generic (generic-hwe-22.04),
6.5.0-17-generic,
6.5.0-14-generic (generic-hwe-22.04-kfocus) (meta purged).
- Running kernel is 6.5.0-17-generic (generic-hwe-22.04) per assert.
- Blessed kernel is NOT FOUND because meta not installed per assert.
- /boot is NOT its own partition with 1482 free of 2048M.
- Check Forced: -f flag used.
- Results in PURGE
-- 6.5.0-21-generic is the highest version for minimum, so retrained.
-- 6.5.0-17-generic is running kernel, so retrained.
-- 6.5.0-14-generic is PURGED because it is not blessed.
--- generic-hwe-22.04-kfocus meta is not in package list.
-- Root disk free space < 10GB, so effective size is 1482/8 = 185.
-- Effective free size is free 185-(3*230) = -505
--- There is NOT enough room for one more kernel (-505 < 230M).
--- This is low space when total space only allows (-505/230 = -2) kernels.
-- IN ADDITION, report is presented due to force flag.
;-f;y;6.5.0-17-generic;n;1482,2048;0;
linux-base
linux-firmware
linux-generic-hwe-22.04
linux-headers-6.5.0-14-generic
linux-headers-6.5.0-17-generic
linux-headers-6.5.0-21-generic
linux-headers-generic-hwe-22.04
linux-hwe-6.5-headers-6.5.0-14
linux-hwe-6.5-headers-6.5.0-17
linux-hwe-6.5-headers-6.5.0-21
linux-hwe-6.5-tools-6.5.0-14
linux-hwe-6.5-tools-6.5.0-17
linux-hwe-6.5-tools-6.5.0-21
linux-image-6.5.0-14-generic
linux-image-6.5.0-17-generic
linux-image-6.5.0-21-generic
linux-image-generic-hwe-22.04
linux-libc-dev
linux-modules-6.5.0-14-generic
linux-modules-6.5.0-17-generic
linux-modules-6.5.0-21-generic
linux-modules-extra-6.5.0-14-generic
linux-modules-extra-6.5.0-17-generic
linux-modules-extra-6.5.0-21-generic
linux-sound-base
linux-tools-6.5.0-14-generic
linux-tools-6.5.0-17-generic
linux-tools-6.5.0-21-generic
linux-tools-common
linux-tools-generic-hwe-22.04'

  '_012 Installed kernels are:
6.5.0-21-generic (generic-hwe-22.04),
6.5.0-17-generic,
6.5.0-14-generic (generic-hwe-22.04-kfocus) (meta purged).
- Running kernel is 6.5.0-21-generic (generic-hwe-22.04) per assert.
- Blessed kernel is 6.5.0-14-generic because meta installed per assert.
- /boot is NOT its own partition with 1482 free of 2048M.
- Check Forced: -f flag used.
- Results in PURGE BECAUSE:
-- 6.5.0-21-generic is running kernel, so retained.
-- 6.5.0-14-generic is blessed kernel, so retained.
-- 6.5.0-17-generic is not running or blessed, so purged.
-- Root disk free space < 10GB, so effective size is 1482/8 = 185.
-- Effective free size is free 185-(3*230) = -505
--- There is NOT enough room for one more kernel (-505 < 230M).
--- This is low space when total space only allows (-505/230 = -2) kernels.
-- IN ADDITION, report is presented due to force flag.
;-f;y;6.5.0-21-generic;n;1482,2048;0;
linux-base
linux-firmware
linux-generic-hwe-22.04
linux-generic-hwe-22.04-kfocus
linux-headers-6.5.0-14-generic
linux-headers-6.5.0-17-generic
linux-headers-6.5.0-21-generic
linux-headers-generic-hwe-22.04
linux-headers-generic-hwe-22.04-kfocus
linux-hwe-6.5-headers-6.5.0-14
linux-hwe-6.5-headers-6.5.0-17
linux-hwe-6.5-headers-6.5.0-21
linux-hwe-6.5-tools-6.5.0-14
linux-hwe-6.5-tools-6.5.0-17
linux-hwe-6.5-tools-6.5.0-21
linux-image-6.5.0-14-generic
linux-image-6.5.0-17-generic
linux-image-6.5.0-21-generic
linux-image-generic-hwe-22.04
linux-image-generic-hwe-22.04-kfocus
linux-libc-dev
linux-modules-6.5.0-14-generic
linux-modules-6.5.0-17-generic
linux-modules-6.5.0-21-generic
linux-modules-extra-6.5.0-14-generic
linux-modules-extra-6.5.0-17-generic
linux-modules-extra-6.5.0-21-generic
linux-sound-base
linux-tools-6.5.0-14-generic
linux-tools-6.5.0-17-generic
linux-tools-6.5.0-21-generic
linux-tools-common
linux-tools-generic-hwe-22.04
linux-tools-generic-hwe-22.04-kfocus'

  '_013 Installed kernels are:
6.5.0-21-generic (generic-hwe-22.04),
6.5.0-17-generic,
6.5.0-14-generic (generic-hwe-22.04-kfocus) (meta purged).
- Running kernel is 6.5.0-21-generic (generic-hwe-22.04) per assert.
- Blessed kernel is 6.5.0-14-generic because meta installed per assert.
- /boot is NOT its own partition with 101482 free of 102048M.
- Check Forced: -f flag used.
- Results in no action BECAUSE:
-- Root disk free space > 10GB, so effective size is 8 * 230.
-- Threshold to offer purge is 8 - 3
-- There are 3 kernels installed, so below threshold
 -- HOWEVER, report is presented due to force flag.
;-f;y;6.5.0-21-generic;n;101482,102048;0;
linux-base
linux-firmware
linux-generic-hwe-22.04
linux-generic-hwe-22.04-kfocus
linux-headers-6.5.0-14-generic
linux-headers-6.5.0-17-generic
linux-headers-6.5.0-21-generic
linux-headers-generic-hwe-22.04
linux-headers-generic-hwe-22.04-kfocus
linux-hwe-6.5-headers-6.5.0-14
linux-hwe-6.5-headers-6.5.0-17
linux-hwe-6.5-headers-6.5.0-21
linux-hwe-6.5-tools-6.5.0-14
linux-hwe-6.5-tools-6.5.0-17
linux-hwe-6.5-tools-6.5.0-21
linux-image-6.5.0-14-generic
linux-image-6.5.0-17-generic
linux-image-6.5.0-21-generic
linux-image-generic-hwe-22.04
linux-image-generic-hwe-22.04-kfocus
linux-libc-dev
linux-modules-6.5.0-14-generic
linux-modules-6.5.0-17-generic
linux-modules-6.5.0-21-generic
linux-modules-extra-6.5.0-14-generic
linux-modules-extra-6.5.0-17-generic
linux-modules-extra-6.5.0-21-generic
linux-sound-base
linux-tools-6.5.0-14-generic
linux-tools-6.5.0-17-generic
linux-tools-6.5.0-21-generic
linux-tools-common
linux-tools-generic-hwe-22.04
linux-tools-generic-hwe-22.04-kfocus'

  '.014 Installed kernels are the generic-hwe-22.04-kfocus,
 6.2.0-35-generic, 5.19.0-50-generic, and 5.15.0-97-generic.
- Running kernel is 5.15.0-97-generic.
- /boot is its own partition with 0M free.
- Results in purge for 6.2.0-35-generic and 5.19.0-50-generic.
;;y;5.15.0-97-generic;y;0,500;0;
linux-base
linux-firmware
linux-generic-hwe-22.04-kfocus
linux-headers-6.2.0-35-generic
linux-headers-6.5.0-14-generic
linux-headers-5.19.0-50-generic
linux-headers-5.15.0-97-generic
linux-headers-generic-hwe-22.04-kfocus
linux-hwe-5.19-headers-5.19.0-50
linux-hwe-5.19-tools-5.19.0-50
linux-hwe-6.2-headers-6.2.0-35
linux-hwe-6.2-tools-6.2.0-35
linux-hwe-6.5-headers-6.5.0-14
linux-hwe-6.5-tools-6.5.0-14
linux-image-6.2.0-35-generic
linux-image-6.5.0-14-generic
linux-image-5.19.0-50-generic
linux-image-5.15.0-97-generic
linux-image-generic-hwe-22.04-kfocus
linux-libc-dev
linux-modules-6.2.0-35-generic
linux-modules-6.5.0-14-generic
linux-modules-5.19.0-50-generic
linux-modules-5.15.0-97-generic
linux-modules-extra-6.2.0-35-generic
linux-modules-extra-6.5.0-14-generic
linux-modules-extra-5.19.0-50-generic
linux-modules-extra-5.15.0-97-generic
linux-sound-base
linux-tools-6.2.0-35-generic
linux-tools-6.5.0-14-generic
linux-tools-5.19.0-50-generic
linux-tools-5.15.0-97-generic
linux-tools-common
linux-tools-generic-hwe-22.04-kfocus'

  '_015 Installed Kernels 15 different 6.5.0 kernel variants.
- Running kernel is 6.5.0-17-generic.
- Blessed kernel is 6.5.0-14-generic because meta installed per assert.
/boot is on root disk. Sizes are 11610,16460 (avail,size).
- Check forced: Installed 15 >= max (12) - thresholds (2)
- Results in purge keeping 9 (12 - 3) kernels per heuristics
-- PURGED kernels should be
--- linux-image-6.5.0-1014-oracle
--- linux-image-6.5.0-1015-azure
--- linux-image-6.5.0-1015-oracle
--- linux-image-6.5.0-14-lowlatency
--- linux-image-6.5.0-15-generic
--- linux-image-6.5.0-15-lowlatency
;;y;6.5.0-17-generic;n;11610,16460;0;
linux-base
linux-firmware
linux-headers-generic-hwe-22.04-kfocus
linux-image-generic-hwe-22.04-kfocus
linux-libc-dev
linux-sound-base
linux-gcp-6.5-headers-6.5.0-1014
linux-oem-6.5-headers-6.5.0-1014
linux-oracle-6.5-headers-6.5.0-1014
linux-azure-6.5-headers-6.5.0-1015
linux-oracle-6.5-headers-6.5.0-1015
linux-oracle-6.5-headers-6.5.0-1016
linux-hwe-6.5-headers-6.5.0-14
linux-hwe-6.5-headers-6.5.0-15
linux-hwe-6.5-headers-6.5.0-17
linux-hwe-6.5-headers-6.5.0-18
linux-hwe-6.5-headers-6.5.0-21
linux-gcp-6.5-tools-6.5.0-1014
linux-oem-6.5-tools-6.5.0-1014
linux-oracle-6.5-tools-6.5.0-1014
linux-azure-6.5-tools-6.5.0-1015
linux-oracle-6.5-tools-6.5.0-1015
linux-oracle-6.5-tools-6.5.0-1016
linux-hwe-6.5-tools-6.5.0-14
linux-hwe-6.5-tools-6.5.0-15
linux-hwe-6.5-tools-6.5.0-17
linux-hwe-6.5-tools-6.5.0-18
linux-hwe-6.5-tools-6.5.0-21
linux-headers-6.5.0-1014-gcp
linux-headers-6.5.0-1014-oem
linux-headers-6.5.0-1014-oracle
linux-headers-6.5.0-1015-azure
linux-headers-6.5.0-1015-oracle
linux-headers-6.5.0-1016-oracle
linux-headers-6.5.0-14-generic
linux-headers-6.5.0-14-lowlatency
linux-headers-6.5.0-15-generic
linux-headers-6.5.0-15-lowlatency
linux-headers-6.5.0-17-generic
linux-headers-6.5.0-17-lowlatency
linux-headers-6.5.0-18-generic
linux-headers-6.5.0-21-generic
linux-image-6.5.0-1014-gcp
linux-image-6.5.0-1014-oem
linux-image-6.5.0-1014-oracle
linux-image-6.5.0-1015-azure
linux-image-6.5.0-1015-azure-fde
linux-image-6.5.0-1015-oracle
linux-image-6.5.0-1016-oracle
linux-image-6.5.0-14-generic
linux-image-6.5.0-14-lowlatency
linux-image-6.5.0-15-generic
linux-image-6.5.0-15-lowlatency
linux-image-6.5.0-17-generic
linux-image-6.5.0-17-lowlatency
linux-image-6.5.0-18-generic
linux-image-6.5.0-21-generic
linux-modules-6.5.0-1014-gcp
linux-modules-6.5.0-1014-oem
linux-modules-6.5.0-1014-oracle
linux-modules-6.5.0-1015-azure
linux-modules-6.5.0-1015-oracle
linux-modules-6.5.0-1016-oracle
linux-modules-6.5.0-14-generic
linux-modules-6.5.0-14-lowlatency
linux-modules-6.5.0-15-generic
linux-modules-6.5.0-15-lowlatency
linux-modules-6.5.0-17-generic
linux-modules-6.5.0-17-lowlatency
linux-modules-6.5.0-18-generic
linux-modules-6.5.0-21-generic
linux-modules-extra-6.5.0-1014-gcp
linux-modules-extra-6.5.0-1014-oracle
linux-modules-extra-6.5.0-1015-azure
linux-modules-extra-6.5.0-1015-oracle
linux-modules-extra-6.5.0-1016-oracle
linux-modules-extra-6.5.0-14-generic
linux-modules-extra-6.5.0-15-generic
linux-modules-extra-6.5.0-17-generic
linux-modules-extra-6.5.0-18-generic
linux-modules-extra-6.5.0-21-generic
linux-tools-6.5.0-1014-gcp
linux-tools-6.5.0-1014-oem
linux-tools-6.5.0-1014-oracle
linux-tools-6.5.0-1015-azure
linux-tools-6.5.0-1015-oracle
linux-tools-6.5.0-1016-oracle
linux-tools-6.5.0-14-generic
linux-tools-6.5.0-14-lowlatency
linux-tools-6.5.0-15-generic
linux-tools-6.5.0-15-lowlatency
linux-tools-6.5.0-17-generic
linux-tools-6.5.0-17-lowlatency
linux-tools-6.5.0-18-generic
linux-tools-6.5.0-21-generic'

  '_016 Installed Kernels 12 different 6.5.0 kernel variants.
- Running kernel is 6.5.0-1014-gcp.
- Blessed kernel is 6.5.0-14-generic because meta installed per assert.
- /boot is on root disk. Sizes are 11610,16460 (avail,size).
- Check forced: installed 12 >= max (12) - thresholds (2)
- Results in purge keeping 9 (12 - 3) kernels per heuristics
-- PURGED kernels should be
--- linux-image-6.5.0-1014-oracle
--- linux-image-6.5.0-1015-azure
--- linux-image-6.5.0-17-generic
;;y;6.5.0-1014-gcp;n;11610,16460;0;
linux-base
linux-firmware
linux-headers-generic-hwe-22.04-kfocus
linux-image-generic-hwe-22.04-kfocus
linux-libc-dev
linux-sound-base
linux-gcp-6.5-headers-6.5.0-1014
linux-oem-6.5-headers-6.5.0-1014
linux-azure-6.5-headers-6.5.0-1015
linux-oracle-6.5-headers-6.5.0-1014
linux-oracle-6.5-headers-6.5.0-1016
linux-hwe-6.5-headers-6.5.0-14
linux-hwe-6.5-headers-6.5.0-15
linux-hwe-6.5-headers-6.5.0-17
linux-hwe-6.5-headers-6.5.0-18
linux-hwe-6.5-headers-6.5.0-21
linux-gcp-6.5-tools-6.5.0-1014
linux-oem-6.5-tools-6.5.0-1014
linux-azure-6.5-tools-6.5.0-1015
linux-oracle-6.5-tools-6.5.0-1014
linux-oracle-6.5-tools-6.5.0-1016
linux-hwe-6.5-tools-6.5.0-14
linux-hwe-6.5-tools-6.5.0-15
linux-hwe-6.5-tools-6.5.0-17
linux-hwe-6.5-tools-6.5.0-18
linux-hwe-6.5-tools-6.5.0-21
linux-headers-6.5.0-1014-gcp
linux-headers-6.5.0-1014-oracle
linux-headers-6.5.0-1014-oem
linux-headers-6.5.0-1015-azure
linux-headers-6.5.0-1016-oracle
linux-headers-6.5.0-14-generic
linux-headers-6.5.0-15-lowlatency
linux-headers-6.5.0-17-generic
linux-headers-6.5.0-17-lowlatency
linux-headers-6.5.0-18-generic
linux-headers-6.5.0-21-generic
linux-image-6.5.0-1014-gcp
linux-image-6.5.0-1014-oem
linux-image-6.5.0-1014-oracle
linux-image-6.5.0-1015-azure
linux-image-6.5.0-1015-azure-fde
linux-image-6.5.0-1016-oracle
linux-image-6.5.0-14-generic
linux-image-6.5.0-15-lowlatency
linux-image-6.5.0-17-generic
linux-image-6.5.0-17-lowlatency
linux-image-6.5.0-18-generic
linux-image-6.5.0-21-generic
linux-modules-6.5.0-1014-gcp
linux-modules-6.5.0-1014-oem
linux-modules-6.5.0-1014-oracle
linux-modules-6.5.0-1015-azure
linux-modules-6.5.0-1016-oracle
linux-modules-6.5.0-14-generic
linux-modules-6.5.0-15-lowlatency
linux-modules-6.5.0-17-generic
linux-modules-6.5.0-17-lowlatency
linux-modules-6.5.0-18-generic
linux-modules-6.5.0-21-generic
linux-modules-extra-6.5.0-1014-gcp
linux-modules-extra-6.5.0-1014-oracle
linux-modules-extra-6.5.0-1015-azure
linux-modules-extra-6.5.0-1016-oracle
linux-modules-extra-6.5.0-14-generic
linux-modules-extra-6.5.0-17-generic
linux-modules-extra-6.5.0-18-generic
linux-modules-extra-6.5.0-21-generic
linux-tools-6.5.0-1014-gcp
linux-tools-6.5.0-1014-oem
linux-tools-6.5.0-1014-oracle
linux-tools-6.5.0-1015-azure
linux-tools-6.5.0-1016-oracle
linux-tools-6.5.0-14-generic
linux-tools-6.5.0-15-lowlatency
linux-tools-6.5.0-17-generic
linux-tools-6.5.0-17-lowlatency
linux-tools-6.5.0-18-generic
linux-tools-6.5.0-21-generic'

  '_017 Installed Kernels 11 different 6.5.0 kernel variants.
- Running kernel is 6.5.0-1014-gcp.
- Blessed kernel is 6.5.0-14-generic because meta installed per assert.
- /boot is on root disk. Sizes are 11610,16460 (avail,size).
- Check forced: installed 11 >= max (12) - thresholds (2)
- Results in purge keeping 9 (12 - 3) kernels per heuristics
-- PURGED kernels should be
--- linux-image-6.5.0-1014-oracle
--- linux-image-6.5.0-1015-azure
;;y;6.5.0-1014-gcp;n;11610,16460;0;
linux-base
linux-firmware
linux-headers-generic-hwe-22.04-kfocus
linux-image-generic-hwe-22.04-kfocus
linux-libc-dev
linux-sound-base
linux-gcp-6.5-headers-6.5.0-1014
linux-oem-6.5-headers-6.5.0-1014
linux-azure-6.5-headers-6.5.0-1015
linux-oracle-6.5-headers-6.5.0-1014
linux-oracle-6.5-headers-6.5.0-1016
linux-hwe-6.5-headers-6.5.0-14
linux-hwe-6.5-headers-6.5.0-15
linux-hwe-6.5-headers-6.5.0-17
linux-hwe-6.5-headers-6.5.0-18
linux-hwe-6.5-headers-6.5.0-21
linux-gcp-6.5-tools-6.5.0-1014
linux-oem-6.5-tools-6.5.0-1014
linux-azure-6.5-tools-6.5.0-1015
linux-oracle-6.5-tools-6.5.0-1014
linux-oracle-6.5-tools-6.5.0-1016
linux-hwe-6.5-tools-6.5.0-14
linux-hwe-6.5-tools-6.5.0-15
linux-hwe-6.5-tools-6.5.0-17
linux-hwe-6.5-tools-6.5.0-18
linux-hwe-6.5-tools-6.5.0-21
linux-headers-6.5.0-1014-gcp
linux-headers-6.5.0-1014-oracle
linux-headers-6.5.0-1014-oem
linux-headers-6.5.0-1015-azure
linux-headers-6.5.0-1016-oracle
linux-headers-6.5.0-14-generic
linux-headers-6.5.0-15-lowlatency
linux-headers-6.5.0-17-lowlatency
linux-headers-6.5.0-18-generic
linux-headers-6.5.0-21-generic
linux-image-6.5.0-1014-gcp
linux-image-6.5.0-1014-oem
linux-image-6.5.0-1014-oracle
linux-image-6.5.0-1015-azure
linux-image-6.5.0-1015-azure-fde
linux-image-6.5.0-1016-oracle
linux-image-6.5.0-14-generic
linux-image-6.5.0-15-lowlatency
linux-image-6.5.0-17-lowlatency
linux-image-6.5.0-18-generic
linux-image-6.5.0-21-generic
linux-modules-6.5.0-1014-gcp
linux-modules-6.5.0-1014-oem
linux-modules-6.5.0-1014-oracle
linux-modules-6.5.0-1015-azure
linux-modules-6.5.0-1016-oracle
linux-modules-6.5.0-14-generic
linux-modules-6.5.0-15-lowlatency
linux-modules-6.5.0-17-lowlatency
linux-modules-6.5.0-18-generic
linux-modules-6.5.0-21-generic
linux-modules-extra-6.5.0-1014-gcp
linux-modules-extra-6.5.0-1014-oracle
linux-modules-extra-6.5.0-1015-azure
linux-modules-extra-6.5.0-1016-oracle
linux-modules-extra-6.5.0-14-generic
linux-modules-extra-6.5.0-18-generic
linux-modules-extra-6.5.0-21-generic
linux-tools-6.5.0-1014-gcp
linux-tools-6.5.0-1014-oem
linux-tools-6.5.0-1014-oracle
linux-tools-6.5.0-1015-azure
linux-tools-6.5.0-1016-oracle
linux-tools-6.5.0-14-generic
linux-tools-6.5.0-15-lowlatency
linux-tools-6.5.0-17-lowlatency
linux-tools-6.5.0-18-generic
linux-tools-6.5.0-21-generic'

  '_018 Installed Kernels 10 different 6.5.0 kernel variants.
- Running kernel is 6.5.0-1014-gcp.
- Blessed kernel is 6.5.0-14-generic because meta installed per assert.
- /boot is on root disk. Sizes are 11610,16460 (avail,size).
- Check forced: installed 10 >= max (12) - thresholds (2)
- Results in purge keeping 9 (12 - 3) kernels per heuristics
-- PURGED kernels should be
--- linux-image-6.5.0-1014-oracle
;;y;6.5.0-1014-gcp;n;11610,16460;0;
linux-base
linux-firmware
linux-headers-generic-hwe-22.04-kfocus
linux-image-generic-hwe-22.04-kfocus
linux-libc-dev
linux-sound-base
linux-gcp-6.5-headers-6.5.0-1014
linux-oem-6.5-headers-6.5.0-1014
linux-azure-6.5-headers-6.5.0-1015
linux-oracle-6.5-headers-6.5.0-1014
linux-oracle-6.5-headers-6.5.0-1016
linux-hwe-6.5-headers-6.5.0-14
linux-hwe-6.5-headers-6.5.0-15
linux-hwe-6.5-headers-6.5.0-17
linux-hwe-6.5-headers-6.5.0-18
linux-hwe-6.5-headers-6.5.0-21
linux-gcp-6.5-tools-6.5.0-1014
linux-oem-6.5-tools-6.5.0-1014
linux-azure-6.5-tools-6.5.0-1015
linux-oracle-6.5-tools-6.5.0-1014
linux-oracle-6.5-tools-6.5.0-1016
linux-hwe-6.5-tools-6.5.0-14
linux-hwe-6.5-tools-6.5.0-15
linux-hwe-6.5-tools-6.5.0-17
linux-hwe-6.5-tools-6.5.0-18
linux-hwe-6.5-tools-6.5.0-21
linux-headers-6.5.0-1014-gcp
linux-headers-6.5.0-1014-oracle
linux-headers-6.5.0-1014-oem
linux-headers-6.5.0-1015-azure
linux-headers-6.5.0-1016-oracle
linux-headers-6.5.0-14-generic
linux-headers-6.5.0-15-lowlatency
linux-headers-6.5.0-17-lowlatency
linux-headers-6.5.0-18-generic
linux-headers-6.5.0-21-generic
linux-image-6.5.0-1014-gcp
linux-image-6.5.0-1014-oem
linux-image-6.5.0-1014-oracle
linux-image-6.5.0-1015-azure-fde
linux-image-6.5.0-1016-oracle
linux-image-6.5.0-14-generic
linux-image-6.5.0-15-lowlatency
linux-image-6.5.0-17-lowlatency
linux-image-6.5.0-18-generic
linux-image-6.5.0-21-generic
linux-modules-6.5.0-1014-gcp
linux-modules-6.5.0-1014-oem
linux-modules-6.5.0-1014-oracle
linux-modules-6.5.0-1015-azure
linux-modules-6.5.0-1016-oracle
linux-modules-6.5.0-14-generic
linux-modules-6.5.0-15-lowlatency
linux-modules-6.5.0-17-lowlatency
linux-modules-6.5.0-18-generic
linux-modules-6.5.0-21-generic
linux-modules-extra-6.5.0-1014-gcp
linux-modules-extra-6.5.0-1014-oracle
linux-modules-extra-6.5.0-1015-azure
linux-modules-extra-6.5.0-1016-oracle
linux-modules-extra-6.5.0-14-generic
linux-modules-extra-6.5.0-18-generic
linux-modules-extra-6.5.0-21-generic
linux-tools-6.5.0-1014-gcp
linux-tools-6.5.0-1014-oem
linux-tools-6.5.0-1014-oracle
linux-tools-6.5.0-1015-azure
linux-tools-6.5.0-1016-oracle
linux-tools-6.5.0-14-generic
linux-tools-6.5.0-15-lowlatency
linux-tools-6.5.0-17-lowlatency
linux-tools-6.5.0-18-generic
linux-tools-6.5.0-21-generic'

  '_019 Installed Kernels 9 different 6.5.0 kernel variants.
- Running kernel is 6.5.0-1014-gcp.
- Blessed kernel is 6.5.0-14-generic because meta installed per assert.
- /boot is on root disk. Sizes are 11610,16460 (avail,size).
- Check NOT forced: free_count (3) > threshold (2) when space for 5+ kernels
  is present
- Results: NO ACTION
;;y;6.5.0-1014-gcp;n;11610,16460;0;
linux-base
linux-firmware
linux-headers-generic-hwe-22.04-kfocus
linux-image-generic-hwe-22.04-kfocus
linux-libc-dev
linux-sound-base
linux-gcp-6.5-headers-6.5.0-1014
linux-oem-6.5-headers-6.5.0-1014
linux-azure-6.5-headers-6.5.0-1015
linux-oracle-6.5-headers-6.5.0-1016
linux-hwe-6.5-headers-6.5.0-14
linux-hwe-6.5-headers-6.5.0-15
linux-hwe-6.5-headers-6.5.0-17
linux-hwe-6.5-headers-6.5.0-18
linux-hwe-6.5-headers-6.5.0-21
linux-gcp-6.5-tools-6.5.0-1014
linux-oem-6.5-tools-6.5.0-1014
linux-azure-6.5-tools-6.5.0-1015
linux-oracle-6.5-tools-6.5.0-1016
linux-hwe-6.5-tools-6.5.0-14
linux-hwe-6.5-tools-6.5.0-15
linux-hwe-6.5-tools-6.5.0-17
linux-hwe-6.5-tools-6.5.0-18
linux-hwe-6.5-tools-6.5.0-21
linux-headers-6.5.0-1014-gcp
linux-headers-6.5.0-1014-oem
linux-headers-6.5.0-1015-azure
linux-headers-6.5.0-1016-oracle
linux-headers-6.5.0-14-generic
linux-headers-6.5.0-15-lowlatency
linux-headers-6.5.0-17-lowlatency
linux-headers-6.5.0-18-generic
linux-headers-6.5.0-21-generic
linux-image-6.5.0-1014-gcp
linux-image-6.5.0-1014-oem
linux-image-6.5.0-1015-azure-fde
linux-image-6.5.0-1016-oracle
linux-image-6.5.0-14-generic
linux-image-6.5.0-15-lowlatency
linux-image-6.5.0-17-lowlatency
linux-image-6.5.0-18-generic
linux-image-6.5.0-21-generic
linux-modules-6.5.0-1014-gcp
linux-modules-6.5.0-1014-oem
linux-modules-6.5.0-1015-azure
linux-modules-6.5.0-1016-oracle
linux-modules-6.5.0-14-generic
linux-modules-6.5.0-15-lowlatency
linux-modules-6.5.0-17-lowlatency
linux-modules-6.5.0-18-generic
linux-modules-6.5.0-21-generic
linux-modules-extra-6.5.0-1014-gcp
linux-modules-extra-6.5.0-1015-azure
linux-modules-extra-6.5.0-1016-oracle
linux-modules-extra-6.5.0-14-generic
linux-modules-extra-6.5.0-18-generic
linux-modules-extra-6.5.0-21-generic
linux-tools-6.5.0-1014-gcp
linux-tools-6.5.0-1014-oem
linux-tools-6.5.0-1015-azure
linux-tools-6.5.0-1016-oracle
linux-tools-6.5.0-14-generic
linux-tools-6.5.0-15-lowlatency
linux-tools-6.5.0-17-lowlatency
linux-tools-6.5.0-18-generic
linux-tools-6.5.0-21-generic'

  '_020 Installed Kernels 4 different 6.5.0 kernel variants.
- /boot is its own partition with 350M free of 1150M (avail,size).
- Running kernel is 6.5.0-17-generic.
- Blessed kernel is 6.5.0-14 per mock
- Check forced: Low disk - room for 1 kernel remains
  with 4 installed, but on larger disk up to room for 5 nominal,
  this forces a check.
- Results in purge for 6.5.0-18-generic
;;y;6.5.0-17-generic;y;350,1150;0;
linux-base
linux-firmware
linux-headers-generic-hwe-22.04-kfocus
linux-libc-dev
linux-sound-base
linux-hwe-6.5-headers-6.5.0-14
linux-hwe-6.5-headers-6.5.0-17
linux-hwe-6.5-headers-6.5.0-18
linux-hwe-6.5-headers-6.5.0-21
linux-hwe-6.5-tools-6.5.0-14
linux-hwe-6.5-tools-6.5.0-17
linux-hwe-6.5-tools-6.5.0-18
linux-hwe-6.5-tools-6.5.0-21
linux-headers-6.5.0-14-generic
linux-headers-6.5.0-17-generic
linux-headers-6.5.0-18-generic
linux-headers-6.5.0-21-generic
linux-image-6.5.0-14-generic
linux-image-6.5.0-17-generic
linux-image-6.5.0-18-generic
linux-image-6.5.0-21-generic
linux-image-generic-hwe-22.04-kfocus
linux-modules-6.5.0-14-generic
linux-modules-6.5.0-17-generic
linux-modules-6.5.0-18-generic
linux-modules-6.5.0-21-generic
linux-modules-extra-6.5.0-14-generic
linux-modules-extra-6.5.0-17-generic
linux-modules-extra-6.5.0-18-generic
linux-modules-extra-6.5.0-21-generic
linux-tools-6.5.0-14-generic
linux-tools-6.5.0-17-generic
linux-tools-6.5.0-18-generic
linux-tools-6.5.0-21-generic'

  '_021 Installed Kernels 4 different 6.5.0 kernel variants.
- /boot is its own partition with 500M free of 1150M (avail,size).
- Running kernel is 6.5.0-17-generic.
- Blessed kernel is 6.5.0-14 per mock
- Check NOT forced: free_count (2) > threshold (1) when space for 4-5 kernels
  is present
- Results: NO ACTION
;;y;6.5.0-17-generic;y;500,1150;0;
linux-base
linux-firmware
linux-headers-generic-hwe-22.04-kfocus
linux-libc-dev
linux-sound-base
linux-hwe-6.5-headers-6.5.0-14
linux-hwe-6.5-headers-6.5.0-17
linux-hwe-6.5-headers-6.5.0-18
linux-hwe-6.5-headers-6.5.0-21
linux-hwe-6.5-tools-6.5.0-14
linux-hwe-6.5-tools-6.5.0-17
linux-hwe-6.5-tools-6.5.0-18
linux-hwe-6.5-tools-6.5.0-21
linux-headers-6.5.0-14-generic
linux-headers-6.5.0-17-generic
linux-headers-6.5.0-18-generic
linux-headers-6.5.0-21-generic
linux-image-6.5.0-14-generic
linux-image-6.5.0-17-generic
linux-image-6.5.0-18-generic
linux-image-6.5.0-21-generic
linux-image-generic-hwe-22.04-kfocus
linux-modules-6.5.0-14-generic
linux-modules-6.5.0-17-generic
linux-modules-6.5.0-18-generic
linux-modules-6.5.0-21-generic
linux-modules-extra-6.5.0-14-generic
linux-modules-extra-6.5.0-17-generic
linux-modules-extra-6.5.0-18-generic
linux-modules-extra-6.5.0-21-generic
linux-tools-6.5.0-14-generic
linux-tools-6.5.0-17-generic
linux-tools-6.5.0-18-generic
linux-tools-6.5.0-21-generic'
  
  '_022 Installed kernels are
6.5.0-14-generic (generic-hwe-22.04-kfocus),
6.5.0-17-generic,
6.5.0-21-generic.
- Running kernel is 6.5.0-21-generic per assert.
- Blessed kernel is 6.5.0-14-generic because meta installed per assert.
- /boot is on large root disk but with 500M free.
- Check forced: Low disk space
- Results in purge of only 6.5.0-17-generic BECAUSE:
-- 6.5.0-21-generic is running, so retained.
-- 6.5.0-14-generic is blessed, so retained.
-- 6.5.0-17 IS PURGED because it is not protected, and...
--- There is NOT enough room for one more kernel (effective size is 62MB).
-- ALSO WARN that disk space is low.
;;y;6.5.0-21-generic;n;500,102048;0;
linux-base
linux-firmware
linux-generic-hwe-22.04-kfocus
linux-headers-6.5.0-14-generic
linux-headers-6.5.0-17-generic
linux-headers-6.5.0-21-generic
linux-headers-generic-hwe-22.04-kfocus
linux-hwe-6.5-headers-6.5.0-14
linux-hwe-6.5-headers-6.5.0-17
linux-hwe-6.5-headers-6.5.0-21
linux-hwe-6.5-tools-6.5.0-14
linux-hwe-6.5-tools-6.5.0-17
linux-hwe-6.5-tools-6.5.0-21
linux-image-6.5.0-14-generic
linux-image-6.5.0-17-generic
linux-image-6.5.0-21-generic
linux-image-generic-hwe-22.04-kfocus
linux-libc-dev
linux-modules-6.5.0-14-generic
linux-modules-6.5.0-17-generic
linux-modules-6.5.0-21-generic
linux-modules-extra-6.5.0-14-generic
linux-modules-extra-6.5.0-17-generic
linux-modules-extra-6.5.0-21-generic
linux-sound-base
linux-tools-6.5.0-14-generic
linux-tools-6.5.0-17-generic
linux-tools-6.5.0-21-generic
linux-tools-common
linux-tools-generic-hwe-22.04-kfocus'
  
  '_023 Installed kernels are
6.8.0-31-generic,
6.8.0-35-generic (UNSIGNED!),
6.8.0-35-kfocus (UNSIGNED!),
6.8.0-36-kfocus (UNSIGNED!).
- Running kernel is 6.8.0-36-kfocus per assert.
- Blessed kernel is 6.8.0-36-kfocus because meta installed per assert.
- /boot is on separate partition with 200M free.
- Check forced: Low disk space
- Results in purge of 6.8.0-31-generic and 6.8.0-35-generic BECAUSE:
-- 6.8.0-36-kfocus is running and blessed, so retained.
-- 6.8.0-35-kfocus is of a protected flavor (kfocus) and two kernels are
   being preserved, so retained
-- *-generic kernels ARE PURGED because...
--- There is NOT enough room for any more kernels (effective size is 200MB).
-- ALSO WARN that disk space is low.
;;y;6.8.0-36-kfocus;y;200,800;0;
linux-base
linux-firmware
linux-image-kfocus-24.04-kfocus
linux-headers-6.8.0-31-generic
linux-headers-6.8.0-35-generic
linux-headers-6.8.0-35-kfocus
linux-headers-6.8.0-36-kfocus
linux-image-6.8.0-31-generic
linux-image-unsigned-6.8.0-35-generic
linux-image-unsigned-6.8.0-35-kfocus
linux-image-unsigned-6.8.0-36-kfocus
linux-libc-dev
linux-modules-6.8.0-31-generic
linux-modules-6.8.0-35-generic
linux-modules-6.8.0-35-kfocus
linux-modules-6.8.0-36-kfocus
linux-modules-extra-6.8.0-31-generic
linux-modules-extra-6.8.0-35-generic
linux-modules-extra-6.8.0-35-kfocus
linux-modules-extra-6.8.0-36-kfocus
linux-sound-base
linux-tools-6.8.0-31-generic
linux-tools-6.8.0-35-generic
linux-tools-6.8.0-35-kfocus
linux-tools-6.8.0-36-kfocus
linux-tools-common
linux-tools-kfocus-24.04-kfocus'
  
  '_024 Installed kernels are
6.8.0-31-generic,
6.8.0-35-generic (UNSIGNED!),
6.8.0-35-kfocus (UNSIGNED!),
6.8.0-36-kfocus (UNSIGNED!).
- Running kernel is 6.8.0-36-kfocus per assert.
- Blessed kernel is 6.8.0-36-kfocus because meta installed per assert.
- /boot is on separate partition with 2000M free.
- NO PURGE, because...
-- There is enough room for several more kernels (2000M > 230M)
-- This is NOT low space when total space allows (2600/230 = 11) kernels
;;y;6.8.0-36-kfocus;y;2000,2600;0;
linux-base
linux-firmware
linux-image-kfocus-24.04-kfocus
linux-headers-6.8.0-31-generic
linux-headers-6.8.0-35-generic
linux-headers-6.8.0-35-kfocus
linux-headers-6.8.0-36-kfocus
linux-image-6.8.0-31-generic
linux-image-unsigned-6.8.0-35-generic
linux-image-unsigned-6.8.0-35-kfocus
linux-image-unsigned-6.8.0-36-kfocus
linux-libc-dev
linux-modules-6.8.0-31-generic
linux-modules-6.8.0-35-generic
linux-modules-6.8.0-35-kfocus
linux-modules-6.8.0-36-kfocus
linux-modules-extra-6.8.0-31-generic
linux-modules-extra-6.8.0-35-generic
linux-modules-extra-6.8.0-35-kfocus
linux-modules-extra-6.8.0-36-kfocus
linux-sound-base
linux-tools-6.8.0-31-generic
linux-tools-6.8.0-35-generic
linux-tools-6.8.0-35-kfocus
linux-tools-6.8.0-36-kfocus
linux-tools-common
linux-tools-kfocus-24.04-kfocus'
);
## . END _assertDataTable

## BEGIN _overwriteWithMocksFn {
# Purpose: Overwrite functions from sourced script before running tests
_overwriteWithMocksFn () {
  # 1. _cm2PromptUserFn
  # shellcheck disable=SC2317
  _cm2PromptUserFn () {
    declare _prompt_str _query_type _ans_str;
    _prompt_str="${1:-Continue}";
    _query_type="${3:-}";
    _ans_str="${_assertAnsList[$_assertAnsIdx]}";

    case "${_query_type}" in
      [aw]) _prompt_str="$(_cm2StripTagsFn "${_prompt_str}" 'n')";;
      p) _prompt_str="$(_cm2StripTagsFn "${_prompt_str}" 'y')";
         _prompt_str+="\n\nPress <return> to continue.";;
      *) _prompt_str="$(_cm2StripTagsFn "${_prompt_str}" 'n')";;
    esac
    echo -e "${_prompt_str}" >> "${_runFile}";
    if [[ "${_query_type}" =~ [aw] ]]; then
      echo -e "${_ans_str}" >> "${_runFile}";
    fi
  }

  # 2. (uname -r) for _echoKversRunStrFn and _echoKversFullRunStrFn
  # shellcheck disable=SC2317
  function uname () { echo "${_assertDataList[3]}"; }
  # 3. _echoIsBootMountPointFn
  # shellcheck disable=SC2317
  _echoIsBootMountPointFn () { echo "${_assertDataList[4]}"; }
  # 4. _echoBootMegsFn (used twice, 'size' and 'avail')
  # shellcheck disable=SC2317
  _echoBootMegsFn () {
    declare _idx=1
    [ "${1:-}" = 'size' ] && _idx=2;
    cut -f"${_idx}" -d, <<<"${_assertDataList[5]}";
  }
  # 5. _cm2RunLongCmdFn (return) - this runs the purge
  # shellcheck disable=SC2317
  _cm2RunLongCmdFn () {
    declare _pkg_list _pkg_name _purge_kernel_count _avail_int _size_int;
    echo -e "\nPurge Package List:\n${*:-}\n" >>"${_runFile}";
    shift 3;
    _pkg_list=("$@");
    _purge_kernel_count=0;
    for _pkg_name in "${_pkg_list[@]}"; do
      _cm2WarnStrFn "_pkg_name = ${_pkg_name}";
      if [[ "${_pkg_name}" =~ ^linux-image-[0-9] ]]; then
        (( _purge_kernel_count++ ));
      fi
      _assertDataList[7]="$(
        grep -v "^${_pkg_name}$" <<< "${_assertDataList[7]}"
      )";
    done
    _avail_int="$(_echoBootMegsFn 'avail')";
    _size_int="$(_echoBootMegsFn 'size')";
    (( _avail_int += ( 230 * _purge_kernel_count ) ));
    echo "${_avail_int},${_size_int}" > "${_updateStateFile}";
    echo "${_assertDataList[7]}" >> "${_updateStateFile}";
    return "${_assertDataList[6]}";
  }
  # 7. _echoAptListStrFn
  # shellcheck disable=SC2317
  _echoAptListStrFn () { echo "${_assertDataList[7]}"; }

  # shellcheck disable=SC2317
  _echoMetaKversStrFn () {
    # IMPORTANT: This _aptListStr comes from kfocus-kclean.
    # Be careful; if this changes there, this test will break.
    if [[ "${_assertDataList[7]}" =~ ${1:-} ]]; then
      case "${1:-}" in
        'linux-image-generic-hwe-22.04-kfocus' ) echo '6.5.0-14-generic' ;;
        'linux-image-kfocus-24.04-kfocus' ) echo '6.8.0-36-kfocus' ;;
        *) echo 'XXX_NOT_INSTALLED_XXX';
      esac
    else
      echo 'XXX_NOT_INSTALLED_XXX';
    fi
  }

  _kcleanSetExe='_kcleanSetExe';
  _rollbackSetExe='';
}
## . END _overwriteWithMocksFn }

## BEGIN _unsetMocksFn {
# Purpose : Unset mocked functions and other globals to prevent
#   pollution of namespaces. Mocked functions from commons.2.source are not
#   reset here; instead they are re-source after every test in runUnitTests
#   (the test harness).
#
# If we ever do need to reset a function, this can work, but avoid this
#   technique oin production scripts due to eval:
# _priorCm2PromptUserStr="$(declare -f _cm2PromptUserFn)";
# eval "${_priorCm2PromptUserStr}"; # Restore above function.
#
_unsetMocksFn () {
  # 1. _cm2PromptUserFn
  # 2. (uname -r) for _echoBootInfoStr
  # 3. _echoIsBootMountPointFn
  # 4. _echoBootMegsFn
  # 5. _cm2RunLongCmdFn (return)
  # 6. _echoAptListStrFn
  unset _cm2PromptUserFn uname _echoIsBootMountPointFn _echoBootMegsFn \
    _cm2RunLongCmdFn _attemptInstallRepairFn _echoAptListStrFn \
    _assetDataList _assetAnsList _assertAnsIdx _runFile;
}
## . END _unsetMocksFn }

## BEGIN _runTestFn {
# This MUST be called '_runTestFn' for use by the _runUnitTests
# bashsupport disable=BP2001
_runTestFn () {
  declare _exe_file _fail_count _group_count _group_idx _group_line_str \
    _arg_list _expect_file _check_str;

  # Use function from _runUnitTests: clear out run dir and check expect dir
  if ! _t00ClearRunDirFn;    then return 1; fi
  if ! _t00CheckExpectDirFn; then return 1; fi

  # bashsupport disable=BP2001
  # shellcheck disable=SC2154,SC2034,SC2001,SC2001
  _exe_file="${_t00TopDir}";
  _exe_file+='/package-main/usr/lib/kfocus/bin/kfocus-kclean';

  # Test for CLI version
  # _exe_file+='/r+d/tools/kfocus-kclean-cli';

  # shellcheck disable=SC1090,SC2154
  source "${_exe_file}" || exit 1;
  _doDebug='y'; # Enable debug in sourced file

  # Set environment vars
  export XDG_SESSION_TYPE='tty';

  # The test harness imports _cm2 routines.

  # Overwrite functions with mocks
  _overwriteWithMocksFn;

  ## Begin Iterate through tests {
  _fail_count=0;
  _group_count="${#_assertDataTable[@]}";
  _group_idx=1;
  _assert_idx=1;

  for _group_line_str in "${_assertDataTable[@]}"; do
    _cm2EchoFn "BEGIN Assert ${_group_idx} of ${_group_count}:";

    # Extract _dataList, _ansList, and reset _assertAnsIdx
    readarray -td ';' _assertDataList < <(echo -n "${_group_line_str}");
    readarray -td ' ' _arg_list       < <(echo -n "${_assertDataList[1]}");
    readarray -td ',' _assertAnsList  < <(echo -n "${_assertDataList[2]}");
    _assertAnsIdx=0;

    # Overwrite embedded preferred meta package for repeatability
    if [[ "${_assertDataList[7]}" =~ linux-image-kfocus-24.04-kfocus ]]; then
      _preferredMetaPkg='linux-image-kfocus-24.04-kfocus';
    else
      _preferredMetaPkg='linux-image-generic-hwe-22.04-kfocus';
    fi

    for _str in '' 'a'; do
      # Calculate expect and run files
      # shellcheck disable=SC2154
      _expect_file="$(
        printf '%s/test_%02d%s.txt' "${_t00ExpectDir}" "${_group_idx}" "${_str}"
      )";
      # shellcheck disable=SC2154
      _runFile="$(
        printf '%s/test_%02d%s.txt' "${_t00RunDir}" "${_group_idx}" "${_str}"
      )";
      _updateStateFile="$(
        printf '/tmp/kclean_state_%02d%s.txt' "${_group_idx}" "${_str}"
      )";

      # Remove state file if exists
      if [ -r "${_updateStateFile}" ]; then
        rm "${_updateStateFile}";
      fi

      # Run _mainFn from fixup_kernels with args using mocked functions
      # Reset getopts to work per
      # https://unix.stackexchange.com/questions/233728
      export OPTIND=1;
      _mainFn "${_arg_list[@]}";

      # If first pass, append description
      if [ -z "${_str}" ]; then
        { echo -e '\n=== BEGIN Intention ==============';
          echo -n "${_assertDataList[0]}";
          echo -e '=== . END Intention ==============\n';
        } >> "${_runFile}";
      # If second pass, append update data
      else
        { echo -e '\n=== BEGIN Update  ================';
          echo    "Updated Disk     : ${_assertDataList[5]}";
          echo    "Updated Pkg List :${_assertDataList[7]}";
          echo -e '=== . END Update  ================\n';
        } >> "${_runFile}";
      fi
      # Append debug string for comparison
      # shellcheck disable=SC2154
      echo "${_kc2RtestDebugStr}" >> "${_runFile}";

      ## Begin Check diffs {
      if [ ! -f "${_expect_file}" ]; then touch "${_expect_file}"; fi
      _check_str="$(diff -r --brief "${_expect_file}" "${_runFile}" )";
      if [ -z "${_check_str}" ]; then
        _cm2EchoFn ". OK   assert ${_assert_idx} (${_group_idx}${_str})\n\n";
      else
        _cm2EchoFn 'Please compare expected to run file';
        meld "${_expect_file}" "${_runFile}";
        _cm2EchoFn ". FAIL assert ${_assert_idx} (${_group_idx}${_str})\n\n";
        (( _fail_count++ ));
      fi

      # Prepare data for next run, but only on first pass
      if [ -z "${_str}" ] && [ -r "${_updateStateFile}" ]; then
        _slurp_str="$(cat "${_updateStateFile}")";
        # Assign new disk values
        _assertDataList[5]="$(head -n1 <<< "${_slurp_str}")";
        # Assign new modules list
        _assertDataList[7]="$(tail -n+2 <<< "${_slurp_str}")";
      fi
      (( _assert_idx++ ));
    done
    ## . End Check diffs }
    (( _group_idx++ ));
  done
  ## End Iterate through tests }

  if [ "${_fail_count}" -gt 0 ]; then
    _cm2EchoFn "FAIL: ${_fail_count} of ${_group_count} tests failed.";
  else
    _cm2EchoFn 'OK  : Results match expected';
  fi

  # Revert function names
  _unsetMocksFn;

  return "${_fail_count}";
}
## . END _runTestFn }
