#!/bin/bash
#
# This script only exists so that we can pass multiple commands and their
#   arguments to kwin_wayland.
#
/usr/bin/swaybg --mode fill --image /etc/calamares/branding/kubuntu/wallpaper.png &
xhost si:localuser:root
sudo --preserve-env=XDG_CONFIG_DIRS QT_QPA_PLATFORMTHEME=kde /usr/bin/calamares -D8
