#!/bin/bash

# This script only exists so that we can pass multiple commands and their arguments to kwin_wayland.

/usr/bin/basicwallpaper /usr/share/wallpapers/Next/contents/images/5120x2880.png &
xhost si:localuser:root
sudo QT_QPA_PLATFORMTHEME=kde /usr/bin/calamares -D8
