#!/bin/bash
# Starts the Kubuntu OEM Environment.
export QT_STYLE_OVERRIDE="Breeze"
export BROWSER='sudo -H -u kubuntu firefox'

/usr/bin/kwin_x11 &
/usr/bin/basicwallpaper /usr/share/wallpapers/Next/contents/3840x2160.png &
sudo -E /usr/bin/calamares -D8 # This is intentionally *not* backgrounded.
# If it exits...
killall basicwallpaper
killall kwin_x11
