usr/lib/kfocus/bin/kfocus-rollback
usr/lib/kfocus/bin/kfocus-rollback-set
usr/lib/kfocus/bin/kfocus-snapshot
usr/lib/kfocus/bin/kfocus-btrfs-optimize
src/kfocus-btrfs-reclaim-space/kfocus-btrfs-reclaim-space usr/lib/kfocus/bin/
src/kfocus-report-filefrag/kfocus-report-filefrag usr/lib/kfocus/bin/
usr/lib/kfocus/lib/rollback.2.source
usr/lib/systemd/system/*
usr/share/applications/*
usr/share/icons/*
etc/apt/apt.conf.d/*
