usr/share usr/
usr/lib usr/
layout-default/org.kde.plasma.desktop-layout.js usr/share/plasma/look-and-feel/org.kfocus.desktop/contents/layouts/
layout-default/org.kde.plasma.desktop-layout.js usr/share/plasma/look-and-feel/org.kfocustwilight.desktop/contents/layouts/
layout-default/org.kde.plasma.desktop-layout.js usr/share/plasma/look-and-feel/org.kfocuslight.desktop/contents/layouts/
layout-vert/org.kde.plasma.desktop-layout.js usr/share/plasma/look-and-feel/org.focusvert.desktop/contents/layouts/
layout-vert/org.kde.plasma.desktop-layout.js usr/share/plasma/look-and-feel/org.focusverttwilight.desktop/contents/layouts/
layout-vert/org.kde.plasma.desktop-layout.js usr/share/plasma/look-and-feel/org.focusvertlight.desktop/contents/layouts/
