#!/bin/bash
#
# Copyright 2020-2026 MindShare Inc.
# Written for the Kubuntu Focus by
#   Michael Mikowski, Erich Eickmeyer, and Aaron Rainbolt
#
# NOTES:
# (1) Any X11 configs are unsupported. These are removed over concern with
#    conflicts with XWayland (#6
#
## TODO: Move to tested userspace after expect results verified
#
set -e;

## BEGIN Declare common.2.source symbols {
#  IMPORT 2023-04-04 EXCERPT from common.2.source
#   Symbols are renamed to avoid conflicts with imported lib.
#
_cmXBlockMsg='';
_cmXEchoFn () { echo 1>&2 -e "$*"; }
_cmXSetMsgFn () {
  _cmXBlockMsg="$*";
  _cmXEchoFn "== BEGIN : ${_cmXBlockMsg}";
}
_cmXSucFn () { _cmXEchoFn "== . END : OK   ${_cmXBlockMsg}\n\n"; }
_cmXSucStrFn () { _cmXEchoFn "ok  : ${*}"; }
_cmXWarnFn () { _cmXEchoFn "== . END : WARN Could not ${_cmXBlockMsg}\n\n"; }
_cmXWarnStrFn () { _cmXEchoFn "warn: ${*}"; }
_cmXEscapeRxCharsFn () {
  # shellcheck disable=SC2016
  printf '%s' "${1:-}" | sed 's/[.[\*^$()+?{|]/\\&/g';
}
_cmXChkInstalledPkgFn () {
  declare _pkg_name _status_str;
  _pkg_name="${1:-}";
  _status_str="$( 2>&1 \
    dpkg-query -f '${db:Status-abbrev}' -W "${_pkg_name}"
  )";
  if grep -qE '^.i ' <<< "${_status_str}"; then return 0; fi
  return 1;
}

## . END Declare common.2.source symbols }

## BEGIN _supplementXdgConfigsFn {
# Purpose: Set UX defaults in XDG_CONFIG_DIR kfocus/kf5-settings
#    kglobalshortcutsrc, kcmfont, kdeglobals, kwinrc, and others
#    for consistency.
# 3521, 3802 requires DPI setting it for GTK apps.
#
_supplementXdgConfigsFn () {
  _cmXSetMsgFn 'Use consistent XDG_CONFIG_DIR values';
  if [ -z "${_effectsExe}" ]; then
    _cmXWarnStrFn "Could not find |${_effectsExe}|";
    _cmXWarnFn;
    return;
  fi

  if ! mkdir -p "${_kf5SettingsDir}"; then
    _cmXWarnStrFn "Cannot access |${_kf5SettingsDir}|";
    _cmXWarnFn;
    return;
  fi

  if "${_effectsExe}" -d "${_kf5SettingsDir}"; then
    _cmXSucFn;
  else
    _cmXWarnStrFn "Could not run |${_effectsExe}|";
    _cmXWarnFn;
  fi
}
## . END _supplementXdgConfigsFn }

# hw_config_code 'default' handles hw_model_codes m2g3, m2g2, m2g1, m1g1.
# shellcheck disable=SC2317,SC2329
#
_handle_defaultFn () {
  # target |  source | do_file_backup
  _symlinkTable+=(
    # Clear bigger tty fonts for the HiDPI screen
    '/etc/default/console-setup|'
    # Add   boot params
    '/etc/default/grub.d/kfocus.cfg|/usr/lib/kfocus/conf/dflt-etc_default_grub.d_kfocus.cfg'
    # Clear initramfs config
    '/etc/initramfs-tools/conf.d/kfocus.conf|'
    # Add   general module configs such as sound, nv-power
    '/etc/modprobe.d/kfocus.conf|/usr/lib/kfocus/conf/m2g4-dflt_etc_modprobe.d_kfocus.conf'
    # Add   a list of modules to load on boot such as keyboard, fan on M/XE
    '/etc/modules-load.d/kfocus.conf|/usr/lib/kfocus/conf/etc_modules-load.d_kfocus.conf'
    # Add   a sleep script which toggles xhci and pstate management
    '/usr/lib/systemd/system-sleep/zsleep-kfocus|/usr/lib/kfocus/conf/usr_lib_systemd_system-sleep_zsleep-kfocus'
    # Clear any X11 trackpad config
    '/usr/share/X11/xorg.conf.d/80-kfocus.conf|'
    # Clear any DPI file; this is superseded by _supplementXdgConfigsFn
    '/usr/share/kfocus/kf5-settings/kcmfonts|'
    # Clear any config for TLP, which was deprecated 22.04
    '/etc/tlp.d/kfocus.conf|'
    # Add   kfocus-fand configuration
    '/usr/share/kfocus/kfocus_fand.d/fan_profile_db|/usr/lib/kfocus/conf/dflt-usr_share_kfocus_kfocus_fand.d_fan_profile_db'
    # Clear SDDM service config
    '/etc/systemd/system/sddm.service.d/90-kfocus.conf|'
  );
}

# hw_config_code 'generic' handles model xeg1.
# shellcheck disable=SC2317,SC2329
#
_handle_genericFn () {
  _symlinkTable+=(
    # Clear bigger tty fonts for the HiDPI screen
    '/etc/default/console-setup|'
    # Clear boot params
    '/etc/default/grub.d/kfocus.cfg|'
    # Clear initramfs config
    '/etc/initramfs-tools/conf.d/kfocus.conf|'
    # Clear any general module configs such as sound, nv-power, sound-pop fix
    '/etc/modprobe.d/kfocus.conf|'
    # Add   a list of modules to load on boot such as keyboard, fan on M/XE
    '/etc/modules-load.d/kfocus.conf|/usr/lib/kfocus/conf/etc_modules-load.d_kfocus.conf'
    # Clear a sleep script which toggles xhci and pstate management
    '/usr/lib/systemd/system-sleep/zsleep-kfocus|'
    # Clear any X11 trackpad config
    '/usr/share/X11/xorg.conf.d/80-kfocus.conf|'
    # Clear any DPI file; this is superseded by _supplementXdgConfigsFn
    '/usr/share/kfocus/kf5-settings/kcmfonts|'
    # Clear any config for TLP, which was deprecated 22.04
    '/etc/tlp.d/kfocus.conf|'
    # Add   kfocus-fand configuration
    '/usr/share/kfocus/kfocus_fand.d/fan_profile_db|/usr/lib/kfocus/conf/dflt-usr_share_kfocus_kfocus_fand.d_fan_profile_db'
    # Clear SDDM service config
    '/etc/systemd/system/sddm.service.d/90-kfocus.conf|'
  );
}

# hw_config_code 'xeg2' handles model xeg2.
# shellcheck disable=SC2317,SC2329
#
_handle_xeg2Fn () {
  _symlinkTable+=(
    # Clear bigger tty fonts for the HiDPI screen
    '/etc/default/console-setup|'
    # Add   boot params for to minimize flicker
    '/etc/default/grub.d/kfocus.cfg|/usr/lib/kfocus/conf/m2g4-etc_default_grub.d_kfocus.cfg'
    # Clear initramfs config
    '/etc/initramfs-tools/conf.d/kfocus.conf|'
    # Clear any general module configs such as sound, nv-power, sound-pop fix
    '/etc/modprobe.d/kfocus.conf|'
    # Add   a list of modules to load on boot such as keyboard, fan on M/XE
    '/etc/modules-load.d/kfocus.conf|/usr/lib/kfocus/conf/etc_modules-load.d_kfocus.conf'
    # Add   a sleep script which toggles xhci and pstate management
    '/usr/lib/systemd/system-sleep/zsleep-kfocus|/usr/lib/kfocus/conf/usr_lib_systemd_system-sleep_zsleep-kfocus'
    # Clear any X11 trackpad config
    '/usr/share/X11/xorg.conf.d/80-kfocus.conf|'
    # Clear any DPI file; this is superseded by _supplementXdgConfigsFn
    '/usr/share/kfocus/kf5-settings/kcmfonts|'
    # Clear any config for TLP, which was deprecated 22.04
    '/etc/tlp.d/kfocus.conf|'
    # Add   kfocus-fand configuration
    '/usr/share/kfocus/kfocus_fand.d/fan_profile_db|/usr/lib/kfocus/conf/dflt-usr_share_kfocus_kfocus_fand.d_fan_profile_db'
    # Clear SDDM service config
    '/etc/systemd/system/sddm.service.d/90-kfocus.conf|'
  );
}

# hw_config_code 'xeg3' handles models 14xeg3 and 16xeg3
# shellcheck disable=SC2317,SC2329
#
_handle_xeg3Fn () {
  _symlinkTable+=(
    # Clear bigger tty fonts for the HiDPI screen
    '/etc/default/console-setup|'
    # Add   boot params for to minimize flicker
    '/etc/default/grub.d/kfocus.cfg|/usr/lib/kfocus/conf/xeg3-etc_default_grub.d_kfocus.cfg'
    # Clear initramfs config
    '/etc/initramfs-tools/conf.d/kfocus.conf|'
    # Add   general module configs such as sound, nv-power, sound-pop fix
    '/etc/modprobe.d/kfocus.conf|/usr/lib/kfocus/conf/xeg3-etc_modprobe.d_kfocus.conf'
    # Add   a list of modules to load on boot such as keyboard, fan on M/XE
    '/etc/modules-load.d/kfocus.conf|/usr/lib/kfocus/conf/etc_modules-load.d_kfocus.conf'
    # Add   a sleep script which toggles xhci and pstate management
    '/usr/lib/systemd/system-sleep/zsleep-kfocus|/usr/lib/kfocus/conf/usr_lib_systemd_system-sleep_zsleep-kfocus'
    # Clear any X11 model-specific trackpad config
    '/usr/share/X11/xorg.conf.d/80-kfocus.conf|'
    # Clear any DPI file; this is superseded by _supplementXdgConfigsFn
    '/usr/share/kfocus/kf5-settings/kcmfonts|'
    # Clear any config for TLP, which was deprecated 22.04
    '/etc/tlp.d/kfocus.conf|'
    # Add   kfocus-fand configuration
    '/usr/share/kfocus/kfocus_fand.d/fan_profile_db|/usr/lib/kfocus/conf/dflt-usr_share_kfocus_kfocus_fand.d_fan_profile_db'
    # Clear SDDM service config
    '/etc/systemd/system/sddm.service.d/90-kfocus.conf|'
  );
}

# hw_config_code 'arg1' handles model arg1
# shellcheck disable=SC2317,SC2329
#
_handle_arg1Fn () {
  _symlinkTable+=(
    # Add   bigger tty fonts for the HiDPI screen
    '/etc/default/console-setup|/usr/lib/kfocus/conf/etc_default_console-setup|y'
    # Add   boot params for to minimize flicker
    '/etc/default/grub.d/kfocus.cfg|/usr/lib/kfocus/conf/arg1-etc_default_grub.d_kfocus.cfg'
    # Clear initramfs config
    '/etc/initramfs-tools/conf.d/kfocus.conf|'
    # Clear any general module configs such as sound, nv-power, sound-pop fix
    '/etc/modprobe.d/kfocus.conf|'
    # Add   a list of modules to load on boot such as keyboard, fan on M/XE
    '/etc/modules-load.d/kfocus.conf|/usr/lib/kfocus/conf/etc_modules-load.d_kfocus.conf'
    # Add   a sleep script which toggles xhci and pstate management
    '/usr/lib/systemd/system-sleep/zsleep-kfocus|/usr/lib/kfocus/conf/usr_lib_systemd_system-sleep_zsleep-kfocus'
    # Clear any X11 trackpad config
    '/usr/share/X11/xorg.conf.d/80-kfocus.conf|'
    # Clear any DPI file; this is superseded by _supplementXdgConfigsFn
    '/usr/share/kfocus/kf5-settings/kcmfonts|'
    # Clear any config for TLP, which was deprecated 22.04
    '/etc/tlp.d/kfocus.conf|'
    # Add   kfocus-fand configuration
    '/usr/share/kfocus/kfocus_fand.d/fan_profile_db|/usr/lib/kfocus/conf/dflt-usr_share_kfocus_kfocus_fand.d_fan_profile_db'
    # Add   SDDM service config to allow Gfx init (#6785)
    '/etc/systemd/system/sddm.service.d/90-kfocus.conf|/usr/lib/kfocus/conf/arg1_etc_systemd_system_sddm.service.d_90-kfocus.conf'
  );

  if ! _cmXChkInstalledPkgFn 'kfocus-tools-arg1'; then
    # The tools package changed, so this ensures focusrx installs
    #   kfocus-tools-arg1 on the next login.
    mkdir -p "${_configCodeDir}" || true;
    touch "${_configCodeDir}/hw_reconfig_force" || true;
  fi
}

# hw_config_code 'ir14g1' handles model ir14g1
# shellcheck disable=SC2317,SC2329
#
_handle_ir14g1Fn () {
  _symlinkTable+=(
    # Add   bigger tty fonts for the HiDPI screen
    '/etc/default/console-setup|/usr/lib/kfocus/conf/etc_default_console-setup|y'
    # Add   boot params to minimize flicker
    '/etc/default/grub.d/kfocus.cfg|/usr/lib/kfocus/conf/ir14g1-etc_default_grub.d_kfocus.cfg'
    # Add   No-op config that was once used to minimize intramfs size
    '/etc/initramfs-tools/conf.d/kfocus.conf|/usr/lib/kfocus/conf/nxg1-etc_initramfs-tools_conf.d_kfocus.conf'
    # Clear any general module configs such as sound, nv-power, sound-pop fix
    '/etc/modprobe.d/kfocus.conf|'
    # Clear a list of modules to load on boot such as keyboard, fan on M/XE
    '/etc/modules-load.d/kfocus.conf|'
    # Clear a sleep script which toggles xhci and pstate management
    '/usr/lib/systemd/system-sleep/zsleep-kfocus|'
    # Clear any X11 trackpad config (1)
    #   WAS /usr/lib/kfocus/conf/ir14g1-usr_share_X11_xorg.conf.d_80-kfocus.conf
    '/usr/share/X11/xorg.conf.d/80-kfocus.conf|'
    # Clear any DPI file; this is superseded by _supplementXdgConfigsFn
    '/usr/share/kfocus/kf5-settings/kcmfonts|'
    # Clear any config for TLP, which was deprecated 22.04
    '/etc/tlp.d/kfocus.conf|'
    # Clear kfocus-fand configuration
    '/usr/share/kfocus/kfocus_fand.d/fan_profile_db|'
    # Clear SDDM service config
    '/etc/systemd/system/sddm.service.d/90-kfocus.conf|'
  );
}

# hw_config_code 'ir1Xg2' handles model ir14g2, ir16g2
# shellcheck disable=SC2317,SC2329
#
_handle_ir1Xg2Fn () {
  _symlinkTable+=(
    # Add   bigger tty fonts for the HiDPI screen
    '/etc/default/console-setup|/usr/lib/kfocus/conf/etc_default_console-setup|y'
    # Add   boot params to minimize flicker
    '/etc/default/grub.d/kfocus.cfg|/usr/lib/kfocus/conf/ir1xg2-etc_default_grub.d_kfocus.cfg'
    # Add   No-op config that was once used to minimize intramfs size
    '/etc/initramfs-tools/conf.d/kfocus.conf|/usr/lib/kfocus/conf/nxg1-etc_initramfs-tools_conf.d_kfocus.conf'
    # Clear any general module configs such as sound, nv-power, sound-pop fix
    '/etc/modprobe.d/kfocus.conf|'
    # Clear a list of modules to load on boot such as keyboard, fan on M/XE
    '/etc/modules-load.d/kfocus.conf|'
    # Clear a sleep script which toggles xhci and pstate management
    '/usr/lib/systemd/system-sleep/zsleep-kfocus|'
    # Clear any X11 trackpad config (1)
    #   WAS /usr/lib/kfocus/conf/ir14g1-usr_share_X11_xorg.conf.d_80-kfocus.conf
    '/usr/share/X11/xorg.conf.d/80-kfocus.conf|'
    # Clear any DPI file; this is superseded by _supplementXdgConfigsFn
    '/usr/share/kfocus/kf5-settings/kcmfonts|'
    # Clear any config for TLP, which was deprecated 22.04
    '/etc/tlp.d/kfocus.conf|'
    # Clear kfocus-fand configuration
    '/usr/share/kfocus/kfocus_fand.d/fan_profile_db|'
    # Clear SDDM service config
    '/etc/systemd/system/sddm.service.d/90-kfocus.conf|'
  );
}

# hw_config_code 'ir1Xg3' handles model ir14g3, possibly ir15g3
# shellcheck disable=SC2317,SC2329
#
_handle_ir1Xg3Fn () {
  _symlinkTable+=(
    # Add   bigger tty fonts for the HiDPI screen
    '/etc/default/console-setup|/usr/lib/kfocus/conf/etc_default_console-setup|y'
    # Add   boot params to use deep sleep
    '/etc/default/grub.d/kfocus.cfg|/usr/lib/kfocus/conf/ir1xg3-etc_default_grub.d_kfocus.cfg'
    # Clear initramfs config
    '/etc/initramfs-tools/conf.d/kfocus.conf|'
    # Clear any general module configs such as sound, nv-power, sound-pop fix
    '/etc/modprobe.d/kfocus.conf|'
    # Clear a list of modules to load on boot such as keyboard, fan on M/XE
    '/etc/modules-load.d/kfocus.conf|'
    # Clear a sleep script which toggles xhci and pstate management
    '/usr/lib/systemd/system-sleep/zsleep-kfocus|'
    # Clear any X11 trackpad config (1)
    #   WAS /usr/lib/kfocus/conf/ir1xg3-usr_share_X11_xorg.conf.d_80-kfocus.conf
    '/usr/share/X11/xorg.conf.d/80-kfocus.conf|'
    # Clear any DPI file; this is superseded by _supplementXdgConfigsFn
    '/usr/share/kfocus/kf5-settings/kcmfonts|'
    # Clear any config for TLP, which was deprecated 22.04
    '/etc/tlp.d/kfocus.conf|'
    # Clear kfocus-fand configuration
    '/usr/share/kfocus/kfocus_fand.d/fan_profile_db|'
    # Clear SDDM service config
    '/etc/systemd/system/sddm.service.d/90-kfocus.conf|'
  );
}

# hw_config_code 'm2g4' handles hw_model_codes m2g4
# shellcheck disable=SC2317,SC2329
#
_handle_m2g4Fn () {
  if [ -x "/usr/bin/deb-systemd-helper" ]; then
    deb-systemd-helper mask \
      systemd-backlight@backlight:nvidia_0.service >/dev/null;
  fi
  _symlinkTable+=(
    # Add   bigger tty fonts for the HiDPI screen
    '/etc/default/console-setup|/usr/lib/kfocus/conf/etc_default_console-setup|y'
    # Add   boot params for m2g4
    '/etc/default/grub.d/kfocus.cfg|/usr/lib/kfocus/conf/m2g4-etc_default_grub.d_kfocus.cfg'
    # Clear initramfs config
    '/etc/initramfs-tools/conf.d/kfocus.conf|'
    # Add   general module configs such as sound, nv-power
    '/etc/modprobe.d/kfocus.conf|/usr/lib/kfocus/conf/m2g4-dflt_etc_modprobe.d_kfocus.conf'
    # Add   a list of modules to load on boot such as keyboard, fan on M/XE
    '/etc/modules-load.d/kfocus.conf|/usr/lib/kfocus/conf/etc_modules-load.d_kfocus.conf'
    # Add a sleep script which toggles xhci and pstate management
    '/usr/lib/systemd/system-sleep/zsleep-kfocus|/usr/lib/kfocus/conf/usr_lib_systemd_system-sleep_zsleep-kfocus'
    # Clear any X11 trackpad config (1)
    #   WAS /usr/lib/kfocus/conf/m2g4-usr_share_X11_xorg.conf.d_80-kfocus.conf
    '/usr/share/X11/xorg.conf.d/80-kfocus.conf|'
    # Clear any DPI file; this is superseded by _supplementXdgConfigsFn
    '/usr/share/kfocus/kf5-settings/kcmfonts|'
    # Clear any config for TLP, which was deprecated 22.04
    '/etc/tlp.d/kfocus.conf|'
    # Add   kfocus-fand configuration
    '/usr/share/kfocus/kfocus_fand.d/fan_profile_db|/usr/lib/kfocus/conf/dflt-usr_share_kfocus_kfocus_fand.d_fan_profile_db'
    # Clear SDDM service config
    '/etc/systemd/system/sddm.service.d/90-kfocus.conf|'
  );
}

# hw_config_code 'm2g5' handles hw_model_codes m2g5, m2g5p, m2g5p1 (barlow ridge TB)
# shellcheck disable=SC2317,SC2329
#
_handle_m2g5Fn () {
  declare _symlink _target_file;
  if [ -x "/usr/bin/deb-systemd-helper" ]; then
    deb-systemd-helper mask \
      systemd-backlight@backlight:nvidia_0.service >/dev/null;
  fi
  _symlinkTable+=(
    # Add   bigger tty fonts for the HiDPI screen
    '/etc/default/console-setup|/usr/lib/kfocus/conf/etc_default_console-setup|y'
    # Add   boot params for m2g5
    '/etc/default/grub.d/kfocus.cfg|/usr/lib/kfocus/conf/m2g5-etc_default_grub.d_kfocus.cfg'
    # Clear initramfs config
    '/etc/initramfs-tools/conf.d/kfocus.conf|'
    # Add   general module configs such as sound, nv-power
    '/etc/modprobe.d/kfocus.conf|/usr/lib/kfocus/conf/m2g5-etc_modprobe.d_kfocus.conf'
    # Add   a list of modules to load on boot such as keyboard, fan on M/XE
    '/etc/modules-load.d/kfocus.conf|/usr/lib/kfocus/conf/etc_modules-load.d_kfocus.conf'
    # Add   a sleep script which toggles xhci and pstate management
    '/usr/lib/systemd/system-sleep/zsleep-kfocus|/usr/lib/kfocus/conf/usr_lib_systemd_system-sleep_zsleep-kfocus'
    # Clear any X11 trackpad config (1)
    #   WAS /usr/lib/kfocus/conf/m2g5-usr_share_X11_xorg.conf.d_80-kfocus.conf
    '/usr/share/X11/xorg.conf.d/80-kfocus.conf|'
    # Clear any DPI file; this is superseded by _supplementXdgConfigsFn
    '/usr/share/kfocus/kf5-settings/kcmfonts|'
    # Clear any config for TLP, which was deprecated 22.04
    '/etc/tlp.d/kfocus.conf|'
    # Add   kfocus-fand configuration
    '/usr/share/kfocus/kfocus_fand.d/fan_profile_db|/usr/lib/kfocus/conf/dflt-usr_share_kfocus_kfocus_fand.d_fan_profile_db'
    # Clear SDDM service config
    '/etc/systemd/system/sddm.service.d/90-kfocus.conf|'
  );

  ## Begin Add symlink for m2g5p1 thunderbolt blacklist
  _symlink='/etc/default/grub.d/10_kfocus-tbt.cfg';
  # Consider only if m2g5p1 system
  if [[ "${_dmiName:-}" =~ ^X370SN.*1$ ]]; then
    # Skip taking action if symlink already exists
    if [ -f "${_symlink}" ] || [ -h "${_symlink}" ]; then
      true;
    else
      # Otherwise, blacklist the thunderbolt module
      _target_file='/usr/lib/kfocus/conf/';
      _target_file+='m2g5p1-etc_default_grub.d_10_kfocus-tbt-blacklist.cfg';
      _symlinkTable+=( "${_symlink}|${_target_file}" );
    fi
  fi
  ## . End Add or remove symlink for m2g5p1 thunderbolt blacklist
}
# hw_config_code 'zrg1' handles hw_model_code zrg1, zrg2 5080/5090
# shellcheck disable=SC2317,SC2329
#
_handle_zrg1Fn () {
  if [ -x "/usr/bin/deb-systemd-helper" ]; then
    deb-systemd-helper mask \
      systemd-backlight@backlight:nvidia_0.service >/dev/null;
  fi
  _symlinkTable+=(
    # Add   bigger tty fonts for the HiDPI screen
    '/etc/default/console-setup|/usr/lib/kfocus/conf/etc_default_console-setup|y'
    # Add   boot params
    '/etc/default/grub.d/kfocus.cfg|/usr/lib/kfocus/conf/m2g6-etc_default_grub.d_kfocus.cfg'
    # Clear initramfs config
    '/etc/initramfs-tools/conf.d/kfocus.conf|'
    # Add   general module configs such as sound, nv-power
    '/etc/modprobe.d/kfocus.conf|/usr/lib/kfocus/conf/m2g6-etc_modprobe.d_kfocus.conf'
    # Add   a list of modules to load on boot such as keyboard, fan on M/XE
    '/etc/modules-load.d/kfocus.conf|/usr/lib/kfocus/conf/etc_modules-load.d_kfocus.conf'
    # Add   a sleep script which toggles xhci and pstate management
    '/usr/lib/systemd/system-sleep/zsleep-kfocus|/usr/lib/kfocus/conf/usr_lib_systemd_system-sleep_zsleep-kfocus'
    # Clear any X11 trackpad config (1)
    #   WAS /usr/lib/kfocus/conf/zrg1-usr_share_X11_xorg.conf.d_80-kfocus.conf
    '/usr/share/X11/xorg.conf.d/80-kfocus.conf|'
    # Clear any DPI file; this is superseded by _supplementXdgConfigsFn
    '/usr/share/kfocus/kf5-settings/kcmfonts|'
    # Clear any config for TLP, which was deprecated 22.04
    '/etc/tlp.d/kfocus.conf|'
    # Add   kfocus-fand configuration
    '/usr/share/kfocus/kfocus_fand.d/fan_profile_db|/usr/lib/kfocus/conf/m2g6-usr_share_kfocus_kfocus_fand.d_fan_profile_db'
    # Clear SDDM service config
    '/etc/systemd/system/sddm.service.d/90-kfocus.conf|'
  );
}

# hw_config_code 'm2g6' handles hw_model_codes m2g6, m2g7 5070Ti
# shellcheck disable=SC2317,SC2329
#
_handle_m2g6Fn () {
  if [ -x "/usr/bin/deb-systemd-helper" ]; then
    deb-systemd-helper mask \
      systemd-backlight@backlight:nvidia_0.service >/dev/null;
  fi
  _symlinkTable+=(
    # Add   bigger tty fonts for the HiDPI screen
    '/etc/default/console-setup|/usr/lib/kfocus/conf/etc_default_console-setup|y'
    # Add   boot params
    '/etc/default/grub.d/kfocus.cfg|/usr/lib/kfocus/conf/m2g6-etc_default_grub.d_kfocus.cfg'
    # Clear initramfs config
    '/etc/initramfs-tools/conf.d/kfocus.conf|'
    # Add   general module configs such as sound, nv-power
    '/etc/modprobe.d/kfocus.conf|/usr/lib/kfocus/conf/m2g6-etc_modprobe.d_kfocus.conf'
    # Add   a list of modules to load on boot such as keyboard, fan on M/XE
    '/etc/modules-load.d/kfocus.conf|/usr/lib/kfocus/conf/etc_modules-load.d_kfocus.conf'
    # Add   a sleep script which toggles xhci and pstate management
    '/usr/lib/systemd/system-sleep/zsleep-kfocus|/usr/lib/kfocus/conf/usr_lib_systemd_system-sleep_zsleep-kfocus'
    # Clear any X11 trackpad config (1)
    #   WAS /usr/lib/kfocus/conf/m2g6-usr_share_X11_xorg.conf.d_80-kfocus.conf
    '/usr/share/X11/xorg.conf.d/80-kfocus.conf|'
    # Clear any DPI file; this is superseded by _supplementXdgConfigsFn
    '/usr/share/kfocus/kf5-settings/kcmfonts|'
    # Clear any config for TLP, which was deprecated 22.04
    '/etc/tlp.d/kfocus.conf|'
    # Add   kfocus-fand configuration
    '/usr/share/kfocus/kfocus_fand.d/fan_profile_db|/usr/lib/kfocus/conf/m2g6-usr_share_kfocus_kfocus_fand.d_fan_profile_db'
    # Clear SDDM service config
    '/etc/systemd/system/sddm.service.d/90-kfocus.conf|'
  );
}

# hw_config_code 'nxg1' handles hw_model_codes nxg1, nxg2, nxg3
# shellcheck disable=SC2317,SC2329
#
_handle_nxg1Fn () {
  _symlinkTable+=(
    # Clear bigger tty fonts for the HiDPI screen
    '/etc/default/console-setup|'
    # Add   boot param to prevent flicker
    '/etc/default/grub.d/kfocus.cfg|/usr/lib/kfocus/conf/nxg1-etc_default_grub.d_kfocus.cfg'
    # Add   No-op config that was once used to minimize intramfs size
    '/etc/initramfs-tools/conf.d/kfocus.conf|/usr/lib/kfocus/conf/nxg1-etc_initramfs-tools_conf.d_kfocus.conf'
    # Add   general module configs such as sound, nv-power, sound-pop
    '/etc/modprobe.d/kfocus.conf|/usr/lib/kfocus/conf/nxg1-etc_modprobe.d_kfocus.conf'
    # Clear a list of modules to load on boot such as keyboard, fan on M/XE
    '/etc/modules-load.d/kfocus.conf|'
    # Clear a sleep script which toggles xhci and pstate management
    '/usr/lib/systemd/system-sleep/zsleep-kfocus|'
    # Clear any X11 trackpad config
    '/usr/share/X11/xorg.conf.d/80-kfocus.conf|'
    # Clear any DPI file; this is superseded by _supplementXdgConfigsFn
    '/usr/share/kfocus/kf5-settings/kcmfonts|'
    # Clear any config for TLP, which was deprecated 22.04
    '/etc/tlp.d/kfocus.conf|'
    # Clear kfocus-fand configuration
    '/usr/share/kfocus/kfocus_fand.d/fan_profile_db|'
    # Clear SDDM service config
    '/etc/systemd/system/sddm.service.d/90-kfocus.conf|'
  );
}
# hw_config_code 'other' handles unrecognized hw_model_codes
# shellcheck disable=SC2317,SC2329
#
_handle_otherFn () {
  _symlinkTable+=(
    # Clear bigger tty fonts for the HiDPI screen
    '/etc/default/console-setup|'
    # Clear boot params
    '/etc/default/grub.d/kfocus.cfg|'
    # Clear initramfs config
    '/etc/initramfs-tools/conf.d/kfocus.conf|'
    # Add   general module config to remove sound-pop
    '/etc/modprobe.d/kfocus.conf|/usr/lib/kfocus/conf/nxg1-etc_modprobe.d_kfocus.conf'
    # Clear a list of modules to load on boot such as keyboard, fan on M/XE
    '/etc/modules-load.d/kfocus.conf|'
    # Clear a sleep script which toggles xhci and pstate management
    '/usr/lib/systemd/system-sleep/zsleep-kfocus|'
    # Clear any X11 trackpad config
    '/usr/share/X11/xorg.conf.d/80-kfocus.conf|'
    # Clear any DPI file; this is superseded by _supplementXdgConfigsFn
    '/usr/share/kfocus/kf5-settings/kcmfonts|'
    # Clear any config for TLP, which was deprecated 22.04
    '/etc/tlp.d/kfocus.conf|'
    # Clear kfocus-fand configuration
    '/usr/share/kfocus/kfocus_fand.d/fan_profile_db|'
    # Clear SDDM service config
    '/etc/systemd/system/sddm.service.d/90-kfocus.conf|'
  );
}

_cleanupGrubFileFn () {
  declare _grub_file _grub_line _esc1_rx _str _esc2_rx;
  _cmXSetMsgFn 'Clean up grub file';

  _grub_file='/etc/default/grub';
  _grub_line="$(
    grep -E '^\s*GRUB_CMDLINE_LINUX_DEFAULT="' "${_grub_file}" | tail -n1
  )";

  if [ -z "${_grub_line}" ]; then
    _cmXWarnStrFn "Grub line was not found in |${_grub_file}|.";
    return;
  fi

  _esc1_rx="$(_cmXEscapeRxCharsFn "${_grub_line}")";
  for _str in 'modprobe.blacklist=nouveau' 'modprobe.blacklist=ucsi_acpi' \
    'tpm_tis.interrupts=0' 'acpi_backlight=vendor' 'acpi_os=linux' \
    'acpi_osi=linux'; do
    # shellcheck disable=SC2001
    _grub_line="$(sed "s/\s\+${_str}//" <<<"${_grub_line}")";
  done

  _esc2_rx="$(_cmXEscapeRxCharsFn "${_grub_line}")";
  if [ "${_esc1_rx}" = "${_esc2_rx}" ]; then return; fi

  sed -iE "s/^${_esc1_rx}/\n# KFOCUS-SAVE. See grub.d\/kfocus.cfg for params\n# ${_esc1_rx}\n${_esc2_rx}\n/g" "${_grub_file}" || true;

  _cmXSucFn;
}

_setupSymlinkTableFn () {
  declare _line _msg _do_rm_link _link_list _tgt_dir _cmd_list;
  _cmXSetMsgFn 'Set up symlinks';

  if [ "${#_symlinkTable[@]}" = '0' ]; then
    _cmXWarnStrFn 'No symlinks specified';
    _cmXSucFn;
    return 0;
  fi

  for _line in "${_symlinkTable[@]}"; do
    IFS='|' read -r -a _link_list <<<"${_line}";
    _msg='';
    _do_rm_link='y';

    # Backup target if (a) directed, and ...
    if [ "${_link_list[2]:-}" = 'y' ]; then
      # ... (b) the target is a file and the source exists, and ...
      if [ -f "${_link_list[0]}" ] && [ ! -h "${_link_list[0]}" ] \
        && [ -f "${_link_list[1]}" ]; then
        # ... and the first 512 lines differ
        if [ "$(head -n512 "${_link_list[0]}")" \
          != "$(head -n512 "${_link_list[1]}")" ]; then
          mv "${_link_list[0]}" "${_link_list[0]}.kfocus.$(date +%Y%m%d)" || true;
          _do_rm_link='n';
        fi
      fi
    fi

    # Remove the old link or file
    if [ "${_do_rm_link}" = 'y' ]; then
      _msg="symlink target |${_link_list[0]}|";
      if rm -f "${_link_list[0]}"; then
        _cmXSucStrFn "Removed ${_msg}";
      else
        _cmXWarnStrFn "SKIP: Could not remove ${_msg}";
        continue;
      fi
    fi

    # Do not symlink or copy if the source is empty
    if [ -z "${_link_list[1]}" ]; then continue; fi

    # Validate and optionally create target dir
    _tgt_dir="$(dirname "${_link_list[0]}")";
    if [ -e "${_tgt_dir}" ]; then
      if ! [ -d "${_tgt_dir}" ]; then
        _cmXWarnStrFn "SKIP: Target is NOT a dir |${_tgt_dir}|";
        continue;
      fi
    else
      if ! mkdir -p "${_tgt_dir}"; then
        _cmXWarnStrFn "SKIP: Could not make target dir |${_tgt_dir}|";
        continue;
      fi
    fi

    # Do not symlink or copy and warn if the source not found
    if [ ! -f "${_link_list[1]}" ]; then
      _cmXWarnStrFn "SKIP: Symlink source ${_link_list[1]} not found";
      continue;
    fi

    # Decide to copy or symlink
    _cmd_list=('ln' '-s');
    _msg='symlink';
    if [ "${_link_list[0]}" = '/etc/default/console-setup' ]; then
      _msg='copy';
      _cmd_list=('cp');
    fi
    _msg+=" target ${_link_list[0]}";

    # Execute command and report
    if "${_cmd_list[@]}" "${_link_list[1]}" "${_link_list[0]}"; then
      _cmXSucStrFn "Created ${_msg}";
    else
      _cmXWarnStrFn "Could not create ${_msg}";
    fi

  done

  _cmXSucFn;
}

_setupModelHintsFn () {
  declare _model_code _hints_dir _unique_dir _model_dir \
    _png_list _src_path _img_file _tgt_path _msg;

  _cmXSetMsgFn 'Setup model hints';

  _model_code="${1:-other}";
  _hints_dir='/usr/share/kfocus-hints';

  _unique_dir="${_hints_dir}/unique";
  _model_dir="${_unique_dir}/${_model_code}";

  if [ ! -d "${_model_dir}" ]; then
    _cmXWarnStrFn 'Model dir not found. Using other.';
    _model_dir="${_unique_dir}/other";
  fi

  if [ ! -d "${_model_dir}" ]; then
    _cmXWarnStrFn "Unexpected missing dir: ${_model_dir}";
    _cmXWarnFn;
    return;
  fi

  mapfile -n30 -t _png_list < <(
    find "${_model_dir}" -mindepth 1 -maxdepth 1 -name '*.png' | sort
  );

  for _src_path in "${_png_list[@]}"; do
    _img_file="$(basename "${_src_path}")";
    _tgt_path="${_hints_dir}/${_img_file}";
    if [ ! -f "${_src_path}" ]; then continue; fi

    if [ -e "${_tgt_path}" ]; then
      rm -f "${_tgt_path}" || continue;
    fi

    _msg="symlink target ${_tgt_path}";
    if ln -s "${_src_path}" "${_tgt_path}"; then
      _cmXSucStrFn "Created ${_msg}";
    else
      _cmXWarnStrFn "Could not create ${_msg}";
    fi
  done

  [ -x "${_refreshHintWidgetExe}" ] && "${_refreshHintWidgetExe}" || true;

  _cmXSucFn;
}

_setupBootFn () {
  declare _cmd_table _line _cmd_list;

  _cmXSetMsgFn 'Set up boot configs';
  _cmd_table=(
    '/usr/sbin/depmod'
    '/usr/sbin/update-initramfs -u'
    '/usr/sbin/update-grub'
  );

  for _line in "${_cmd_table[@]}"; do
    IFS=' ' read -r -a _cmd_list <<<"${_line}";
    if [ -x "${_cmd_list[0]}" ]; then
      "${_cmd_list[@]}" || _cmXWarnStrFn "Could not exec ${_cmd_list[*]}";
    fi
  done

  _cmXSucFn;
}

_configFn () {
  declare _config_code_file _old_config_code \
    _lib_file _config_code _fn_name _model_code;

  # Get old config code
  _config_code_file="${_configCodeDir}/hw_config_code";

  if [ -f "${_config_code_file}" ]; then
    _old_config_code="$(cat "${_config_code_file}")";
  else
    _old_config_code='';
  fi

  # Import common and determine config_code from model matrix
  _lib_file='/usr/lib/kfocus/lib/common.2.source';
  _config_code='';
  _model_code='';

  if [ -r "${_lib_file}" ]; then
    # shellcheck disable=1091,1090 source=/usr/lib/kfocus/lib/common.2.source
    source "${_lib_file}" || true;
    if [ "$(type -t _cm2EchoModelStrFn)" = 'function' ]; then
      _model_code="$(_cm2EchoModelStrFn 'code')";
      _config_code="$(_cm2EchoModelStrFn 'config_code')";
    fi
    if [ -f "${_cm2DmiProductNameFile}" ]; then
      _dmiName="$(_cm2CatStripEchoFn "${_cm2DmiProductNameFile}")";
    fi
  fi
  if [ -z "${_config_code:-}" ]; then _config_code='other'; fi
  if [ -z "${_model_code:-}"  ]; then  _model_code='other'; fi

  # If old config code is blank, perform one-time grub cleanup
  if [ -z "${_old_config_code}" ]; then _cleanupGrubFileFn; fi

  # Determine and call per-config-code function
  _fn_name="_handle_${_config_code}Fn";
  if [ "$(type -t "${_fn_name}")" != 'function' ]; then
    _cmXWarnStrFn "Function |${_fn_name}| not found";
    _fn_name='_handle_otherFn';
    _config_code='other';
  fi
  _cmXEchoFn "Hardware config code is |${_config_code}|";

  # Run the found model handler function
  if ! "${_fn_name}"; then
    _cmXWarnStrFn "Function |${_fn_name}| returned an error code";
  fi

  # Inject links for 2357, 2377
  _symlinkTable+=(
    # workaround for Slack
    '/usr/local/bin/xdg-open|/usr/lib/kfocus/conf/usr_local_bin_xdg-open|y'
  );

  # Set up symlinks
  _setupSymlinkTableFn;

  # Run kfocus-reset-effects on XDG_CONFIG_DIR per MODEL
  _supplementXdgConfigsFn;

  # Link hints per MODEL
  _setupModelHintsFn "${_model_code}";

  # Execute commands to set up boot
  _setupBootFn;

  # Save config_code value to a readable file
  mkdir -p "${_configCodeDir}";
  echo "${_config_code}" > "${_config_code_file}" || true;
}

## BEGIN declare and assign package vars {
declare _effectsExe _kf5SettingsDir _dmiName _refreshHintWidgetExe;
_dmiName='';
_effectsExe="$(command -v /usr/lib/kfocus/bin/kfocus-reset-effects || true)";
_refreshHintWidgetExe="$(command -v \
  /usr/lib/kfocus/bin/kfocus-refresh-hint-widget || true)";
_kf5SettingsDir='/usr/share/kfocus/kf5-settings';
_configCodeDir='/var/lib/kfocus';
## . END declare and assign package vars }

# Table line structure is 'target|source|do_safe_backup'
_symlinkTable=();
case "${1:-}" in
  configure|upgrade) _configFn;;
  abort-upgrade|abort-remove|abort-deconfigure) true;;
  *) _cmXWarnStrFn "Unhandled argument |${1:-}|";;
esac
#DEBHELPER#

exit 0;
