#!/bin/bash
# Starts the Kubuntu Live Environment.

export XDG_SESSION_CLASS="user"
export XDG_SESSION_DESKTOP="KDE"
export DESKTOP_SESSION="plasma"
export QT_QPA_PLATFORMTHEME="kde"

if [[ $(cat /proc/cmdline) =~ "oem-config/enable=true" ]]; then
    kwin_wayland --xwayland --no-lockscreen /usr/bin/calamares-launch-oem;
else
    kwin_wayland --xwayland --no-lockscreen kubuntu-installer-prompt;
fi
# If it exits...
startplasma-wayland
