#!/bin/bash

set -e;

deb-systemd-helper disable nvidia-suspend.service;
deb-systemd-helper disable nvidia-hibernate.service;
deb-systemd-helper disable nvidia-resume.service;
deb-systemd-helper disable nvidia-suspend-then-hibernate.service;

deb-systemd-helper disable kfocus-nve-resume.service;
deb-systemd-helper disable kfocus-nve-suspend.service;

# Tag to allow some debhelper commands to inject relevant code
#DEBHELPER#
