#!/bin/bash
# kfocus-nvidia-edge postinst
# This must be run as root. Use set -u to debug.
#
set -e;

## BEGIN Declare common.2.source symbols {
#  IMPORTED on 2022-03-23 EXCERPT from test-scripts/common.2.source
#
_cm2BlockMsg='';
_cm2EchoFn    () { 1>&2 echo -e "$*"; }
_cm2SetMsgFn  () { _cm2BlockMsg="$*"; _cm2EchoFn "== BEGIN : ${_cm2BlockMsg}"; }
_cm2SucFn     () { _cm2EchoFn "== . END : OK   ${_cm2BlockMsg}\n\n"; }
_cm2WarnFn    () { _cm2EchoFn "== . END : WARN Could not ${_cm2BlockMsg}..\n\n"; }
## } . END Declare common.2.source symbols

if ! [ -f /etc/apt/preferences.d/kfocus-nvidia ]; then
  _cm2SetMsgFn "Make sure pinning is available";
  if dpkg-reconfigure kfocus-nvidia-pinning-edge; then
    _cm2SucFn; else _cm2WarnFn;
  fi
fi

# EDGE currently enables nvidia-resume services;
# NON-EDGE currently disables.
#   https://download.nvidia.com/XFree86/
#     Linux-x86_64/570.86.16/README/powermanagement.html
# IMPORTANT: We do NOT use deb-systemd-helper because it does NOT force
#   the units to be activate if previously deactivated. Instead, we
#   use systemctl which does this.
#
_cm2SetMsgFn 'Enable /proc/driver/nvidia/suspend methods';
systemctl enable nvidia-hibernate.service;
systemctl enable nvidia-resume.service;
systemctl enable nvidia-suspend.service;
systemctl enable nvidia-suspend-then-hibernate.service;
_cm2SucFn;

# Tag to allow some debhelper commands to inject relevant code
#DEBHELPER#
