#!/bin/bash
# kfocus-kb-color.postinst
# This must be run as root. Use set -u to debug.
#
set -e;

## BEGIN Declare common.2.source symbols
#  IMPORTED on 2022-03-23 EXCERPT from test-scripts/common.2.source
#
_cm2BlockMsg='';
_cm2EchoFn    () { 1>&2 echo -e "$*"; }
_cm2SetMsgFn  () { _cm2BlockMsg="$*"; _cm2EchoFn "== BEGIN : ${_cm2BlockMsg}"; }
_cm2SucFn     () { _cm2EchoFn "== . END : OK   ${_cm2BlockMsg}\n\n"; }
## . END Declare common.2.source symbols

# IMPORTANT: We do NOT use deb-systemd-helper because it does NOT force
#   the units to be enabled if previously disabled. Instead, we
#   use systemctl ensure this is set every time.
#   deb-systemd-helper also proved problematic.
#
_cm2SetMsgFn 'Enable kbd color save service';
systemctl enable kfocus-kb-save.service || true;
_cm2SucFn;

# Tag to allow some debhelper commands to inject relevant code
#DEBHELPER#
